package com.magicstudios.magiccore.bootstrap;

import com.magicstudios.magiccore.config.model.ToolsFile;import com.magicstudios.magiccore.modules.essentials.WorldPosition;import com.magicstudios.magiccore.modules.tools.*;import com.magicstudios.magiccore.platform.SchedulerFacade;import com.magicstudios.magiccore.protection.*;import com.magicstudios.magiccore.text.MiniMessageRenderer;import net.kyori.adventure.text.Component;import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.inventory.*;import org.bukkit.persistence.PersistentDataType;import org.bukkit.plugin.Plugin;import org.bukkit.util.Vector;
import java.time.*;import java.util.*;

public final class CustomToolController implements Listener,AutoCloseable{
 private final Plugin plugin;private final SchedulerFacade scheduler;private final CustomToolService tools;private final ProtectionService protection;private final Clock clock;private final NamespacedKey toolKey,durabilityKey,levelKey;private final Map<String,NamespacedKey>recipes=new LinkedHashMap<>();private final ToolAreaPlanner planner=new ToolAreaPlanner();
 public CustomToolController(Plugin plugin,SchedulerFacade scheduler,CustomToolService tools,ProtectionService protection,Clock clock,List<ToolsFile.Tool>config){this.plugin=plugin;this.scheduler=scheduler;this.tools=tools;this.protection=protection;this.clock=clock;toolKey=new NamespacedKey(plugin,"custom_tool");durabilityKey=new NamespacedKey(plugin,"tool_durability");levelKey=new NamespacedKey(plugin,"tool_level");registerRecipes(config);}
 public ItemStack create(String id,int level){ToolDefinition definition=tools.require(id);ToolUpgrade upgrade=definition.upgrade(level);ItemStack item=new ItemStack(Material.valueOf(definition.material()));item.editMeta(meta->{meta.displayName(new MiniMessageRenderer().render(definition.displayName()));meta.getPersistentDataContainer().set(toolKey,PersistentDataType.STRING,id);meta.getPersistentDataContainer().set(durabilityKey,PersistentDataType.INTEGER,definition.durability());meta.getPersistentDataContainer().set(levelKey,PersistentDataType.INTEGER,upgrade.level());meta.setUnbreakable(true);meta.lore(List.of(Component.text("Level "+level),Component.text("Durability "+definition.durability()+"/"+definition.durability()),Component.text(upgrade.shape()+" radius="+upgrade.radius()+" depth="+upgrade.depth())));});return item;}
 public boolean upgrade(ItemStack item,int level){String id=item.getPersistentDataContainer().get(toolKey,PersistentDataType.STRING);if(id==null)return false;ToolDefinition definition=tools.require(id);definition.upgrade(level);item.editMeta(meta->{meta.getPersistentDataContainer().set(levelKey,PersistentDataType.INTEGER,level);meta.lore(List.of(Component.text("Level "+level),Component.text("Durability "+durability(item)+"/"+definition.durability()),Component.text(definition.upgrade(level).shape()+" radius="+definition.upgrade(level).radius()+" depth="+definition.upgrade(level).depth())));});return true;}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)
 public void onBreak(BlockBreakEvent event){
  ItemStack held=event.getPlayer().getInventory().getItemInMainHand();
  String id=held.getPersistentDataContainer().get(toolKey,PersistentDataType.STRING);if(id==null)return;
  ToolDefinition definition;try{definition=tools.require(id);}catch(IllegalArgumentException invalid){event.setCancelled(true);event.getPlayer().sendMessage(Component.text("This custom tool definition is unavailable."));return;}
  if(!definition.blockAllowlist().contains(event.getBlock().getType().name()))return;
  event.setCancelled(true);if(!tools.claimCooldown(event.getPlayer().getUniqueId(),id,clock.instant())){event.getPlayer().sendActionBar(Component.text("Tool is cooling down."));return;}
  int level=Optional.ofNullable(held.getPersistentDataContainer().get(levelKey,PersistentDataType.INTEGER)).orElse(1);ToolUpgrade upgrade;try{upgrade=definition.upgrade(level);}catch(IllegalArgumentException invalid){event.getPlayer().sendMessage(Component.text("Invalid tool upgrade level."));return;}
  consumeDurability(event.getPlayer(),held,definition);ToolBlockPosition origin=new ToolBlockPosition(event.getBlock().getX(),event.getBlock().getY(),event.getBlock().getZ());ToolAreaPlanner.Face face=face(event.getPlayer(),event.getBlock());ItemStack dropTool=held.clone();UUID actor=event.getPlayer().getUniqueId();World world=event.getBlock().getWorld();
  for(ToolBlockPosition position:planner.plan(origin,face,upgrade)){Location location=new Location(world,position.x(),position.y(),position.z());scheduler.executeRegion(location,()->{Block block=location.getBlock();String material=block.getType().name();if(!definition.blockAllowlist().contains(material))return;WorldPosition wp=new WorldPosition(world.getUID(),world.getName(),position.x(),position.y(),position.z(),0,0);protection.check(actor,wp,ProtectionAction.BLOCK_BREAK).whenComplete((decision,failure)->scheduler.executeRegion(location,()->{if(failure!=null||!decision.allowed()||!definition.blockAllowlist().contains(block.getType().name()))return;Collection<ItemStack>drops=block.getDrops(dropTool);block.setType(Material.AIR,false);for(int copy=0;copy<upgrade.dropMultiplier();copy++)for(ItemStack drop:drops)world.dropItemNaturally(location,drop.clone());}));});}
 }
 private void consumeDurability(Player player,ItemStack item,ToolDefinition definition){int remaining=durability(item)-1;if(remaining<=0){player.getInventory().setItemInMainHand(null);player.sendMessage(Component.text("Your "+definition.id()+" broke."));return;}item.editMeta(meta->{meta.getPersistentDataContainer().set(durabilityKey,PersistentDataType.INTEGER,remaining);int level=Optional.ofNullable(meta.getPersistentDataContainer().get(levelKey,PersistentDataType.INTEGER)).orElse(1);ToolUpgrade upgrade=definition.upgrade(level);meta.lore(List.of(Component.text("Level "+level),Component.text("Durability "+remaining+"/"+definition.durability()),Component.text(upgrade.shape()+" radius="+upgrade.radius()+" depth="+upgrade.depth())));});}
 private int durability(ItemStack item){return Optional.ofNullable(item.getPersistentDataContainer().get(durabilityKey,PersistentDataType.INTEGER)).orElse(1);}
 private ToolAreaPlanner.Face face(Player player,Block target){Vector delta=target.getLocation().add(.5,.5,.5).toVector().subtract(player.getEyeLocation().toVector());double ax=Math.abs(delta.getX()),ay=Math.abs(delta.getY()),az=Math.abs(delta.getZ());if(ay>=ax&&ay>=az)return delta.getY()>0?ToolAreaPlanner.Face.UP:ToolAreaPlanner.Face.DOWN;if(ax>=az)return delta.getX()>0?ToolAreaPlanner.Face.EAST:ToolAreaPlanner.Face.WEST;return delta.getZ()>0?ToolAreaPlanner.Face.SOUTH:ToolAreaPlanner.Face.NORTH;}
 private void registerRecipes(List<ToolsFile.Tool>configured){for(ToolsFile.Tool tool:configured){if(!tool.recipe().enabled())continue;NamespacedKey key=new NamespacedKey(plugin,"tool_"+tool.id());ShapedRecipe recipe=new ShapedRecipe(key,create(tool.id(),1));recipe.shape(tool.recipe().shape().toArray(String[]::new));tool.recipe().ingredients().forEach((symbol,material)->recipe.setIngredient(symbol.charAt(0),Material.valueOf(material)));if(plugin.getServer().addRecipe(recipe))recipes.put(tool.id(),key);}}
 @Override public void close(){HandlerList.unregisterAll(this);recipes.values().forEach(key->plugin.getServer().removeRecipe(key));recipes.clear();}
}
