package com.magicstudios.magiccore.modules.shop;

import com.magicstudios.magiccore.audit.AuditEvent;
import com.magicstudios.magiccore.audit.AuditService;
import com.magicstudios.magiccore.modules.economy.CurrencyDefinition;
import com.magicstudios.magiccore.modules.economy.EconomyTransactionSupport;
import com.magicstudios.magiccore.modules.worth.ItemValuationService;
import com.magicstudios.magiccore.modules.worth.ValuationInput;
import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;

import java.time.Clock;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

public final class PersistentAdvancedSellService implements AdvancedSellService {
    private final TransactionalDataStore store;private final BatchInventoryRemovalPort inventory;private final ItemValuationService valuation;private final CurrencyDefinition currency;private final AuditService audit;private final Clock clock;private final Duration lifetime;
    private final RecordRepository<SellBatchQuote>quotes=new RecordRepository<>("worth.sell.quote",SellBatchQuote.class);private final RecordRepository<SellReceipt>receipts=new RecordRepository<>("worth.sell.receipt",SellReceipt.class);
    public PersistentAdvancedSellService(TransactionalDataStore store,BatchInventoryRemovalPort inventory,ItemValuationService valuation,CurrencyDefinition currency,AuditService audit,Clock clock,Duration lifetime){this.store=store;this.inventory=inventory;this.valuation=valuation;this.currency=currency;this.audit=audit;this.clock=clock;this.lifetime=lifetime;}
    @Override public CompletionStage<SellBatchQuote>quote(UUID playerId,SellScope scope,String category,List<ValuationInput>snapshot,String operationKey){if(snapshot.size()>500)throw new IllegalArgumentException("SELL_SNAPSHOT_TOO_LARGE");String normalized=category==null?"":category.toLowerCase(Locale.ROOT);Map<Key,SellLine>grouped=new LinkedHashMap<>();
        for(ValuationInput input:snapshot){var value=valuation.value(input);if(!value.sellable()||scope==SellScope.CATEGORY&&!value.category().equalsIgnoreCase(normalized))continue;Key key=new Key(value.fingerprint(),value.itemId(),value.category(),value.unitWorthMinor());SellLine old=grouped.get(key);int quantity=Math.addExact(old==null?0:old.quantity(),value.quantity());long total=Math.multiplyExact(value.unitWorthMinor(),quantity);grouped.put(key,new SellLine(value.fingerprint(),value.itemId(),value.category(),quantity,value.unitWorthMinor(),total));}
        if(grouped.isEmpty())throw new IllegalArgumentException("NO_SELLABLE_ITEMS");List<SellLine>lines=List.copyOf(grouped.values());long credit=lines.stream().mapToLong(SellLine::totalWorthMinor).reduce(0,Math::addExact);return store.transact("advanced-sell-quote:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"advanced-sell-quote",operationKey))throw new IllegalStateException("DUPLICATE_QUOTE_OPERATION");var now=clock.instant();SellBatchQuote quote=new SellBatchQuote(UUID.randomUUID(),playerId,scope,normalized,lines,credit,SellBatchQuote.Status.QUOTED,"","",now,now.plus(lifetime),now);quotes.put(tx,quote.id().toString(),quote,0);return quote;});}
    @Override public CompletionStage<SellReceipt>execute(UUID playerId,UUID quoteId,String operationKey){return reserve(playerId,quoteId,operationKey).thenCompose(quote->{if(quote.status()==SellBatchQuote.Status.SETTLED)return receiptForQuote(quote.id()).thenApply(Optional::orElseThrow);List<BatchInventoryRemovalPort.RemovalLine>lines=quote.lines().stream().map(line->new BatchInventoryRemovalPort.RemovalLine(line.fingerprint(),line.quantity())).toList();return inventory.removeBatchExact(playerId,lines,operationKey).thenCompose(result->result.removed()?markRemoved(quote,result.recoveryPayloadBase64()).thenCompose(this::settle):reject(quote,result.code()).thenCompose(ignored->CompletableFuture.failedFuture(new IllegalStateException(result.code()))));});}
    private CompletionStage<SellBatchQuote>reserve(UUID player,UUID quoteId,String operationKey){return store.transact("advanced-sell-reserve:"+operationKey,tx->{var current=quotes.get(tx,quoteId.toString()).orElseThrow(()->new IllegalArgumentException("QUOTE_NOT_FOUND"));SellBatchQuote quote=current.value();if(!quote.playerId().equals(player))throw new SecurityException("QUOTE_OWNER_MISMATCH");if(quote.status()==SellBatchQuote.Status.SETTLED)return quote;if(!IdempotencyKeys.reserve(tx,"advanced-sell-execute",operationKey))throw new IllegalStateException("DUPLICATE_EXECUTION_OPERATION");if(quote.status()!=SellBatchQuote.Status.QUOTED||!quote.expiresAt().isAfter(clock.instant()))throw new IllegalStateException("QUOTE_UNAVAILABLE");SellBatchQuote reserved=copy(quote,SellBatchQuote.Status.REMOVING,operationKey,quote.recoveryPayloadBase64());quotes.put(tx,quote.id().toString(),reserved,current.revision());return reserved;});}
    private CompletionStage<SellBatchQuote>markRemoved(SellBatchQuote quote,String payload){return store.transact("advanced-sell-removed:"+quote.executionKey(),tx->{var current=quotes.get(tx,quote.id().toString()).orElseThrow();if(current.value().status()!=SellBatchQuote.Status.REMOVING)throw new IllegalStateException("SELL_STATE_CONFLICT");SellBatchQuote removed=copy(current.value(),SellBatchQuote.Status.REMOVED,current.value().executionKey(),payload);quotes.put(tx,quote.id().toString(),removed,current.revision());return removed;});}
    private CompletionStage<SellReceipt>settle(SellBatchQuote quote){return store.transact("advanced-sell-settle:"+quote.executionKey(),tx->{var current=quotes.get(tx,quote.id().toString()).orElseThrow();if(current.value().status()==SellBatchQuote.Status.SETTLED)return receiptByQuote(tx,quote.id()).orElseThrow();if(current.value().status()!=SellBatchQuote.Status.REMOVED)throw new IllegalStateException("SELL_NOT_REMOVED");var applied=EconomyTransactionSupport.credit(tx,quote.playerId(),currency,quote.creditMinor(),quote.executionKey(),quote.playerId().toString(),"item-worth-sell",clock.instant());SellReceipt receipt=new SellReceipt(UUID.randomUUID(),quote.id(),quote.playerId(),currency.id(),quote.lines(),quote.creditMinor(),applied.afterMinor(),applied.transaction().id(),clock.instant());receipts.put(tx,receipt.id().toString(),receipt,0);quotes.put(tx,quote.id().toString(),copy(current.value(),SellBatchQuote.Status.SETTLED,current.value().executionKey(),current.value().recoveryPayloadBase64()),current.revision());return receipt;}).thenCompose(receipt->audit.record(new AuditEvent(UUID.randomUUID(),quote.executionKey(),"ITEMS_SOLD",quote.playerId().toString(),quote.playerId().toString(),Map.of("items",Integer.toString(quote.lines().stream().mapToInt(SellLine::quantity).sum())),Map.of("credit",Long.toString(receipt.creditedMinor()),"receipt",receipt.id().toString()),"MagicCore:ItemWorth",clock.instant())).thenApply(ignored->receipt));}
    private CompletionStage<SellBatchQuote>reject(SellBatchQuote quote,String reason){return store.transact("advanced-sell-reject:"+quote.executionKey(),tx->{var current=quotes.get(tx,quote.id().toString()).orElseThrow();SellBatchQuote rejected=copy(current.value(),SellBatchQuote.Status.REJECTED,current.value().executionKey(),reason);quotes.put(tx,quote.id().toString(),rejected,current.revision());return rejected;});}
    @Override public CompletionStage<Optional<SellReceipt>>receipt(UUID id){return store.read(reader->receipts.get(reader,id.toString()).map(RecordRepository.VersionedValue::value));}
    @Override public CompletionStage<List<SellReceipt>>history(UUID player,int limit){if(limit<1||limit>100)throw new IllegalArgumentException("limit must be 1..100");return store.read(reader->{List<SellReceipt>all=new ArrayList<>();String after=null;while(true){var page=receipts.scanPage(reader,after,1000);page.stream().map(RecordRepository.KeyedVersionedValue::value).filter(value->value.playerId().equals(player)).forEach(all::add);if(page.size()<1000)break;after=page.getLast().key();}return all.stream().sorted(Comparator.comparing(SellReceipt::createdAt).reversed()).limit(limit).toList();});}
    @Override public CompletionStage<Integer>recoverRemoved(){return store.read(reader->{List<SellBatchQuote>pending=new ArrayList<>();String after=null;while(true){var page=quotes.scanPage(reader,after,1000);page.stream().map(RecordRepository.KeyedVersionedValue::value).filter(value->value.status()==SellBatchQuote.Status.REMOVED||value.status()==SellBatchQuote.Status.REMOVING).forEach(pending::add);if(page.size()<1000)break;after=page.getLast().key();}return pending;}).thenCompose(pending->{CompletableFuture<?>[]tasks=pending.stream().map(quote->{if(quote.status()==SellBatchQuote.Status.REMOVED)return settle(quote).toCompletableFuture();return store.transact("advanced-sell-recovery-mark:"+quote.id(),tx->{var current=quotes.get(tx,quote.id().toString()).orElseThrow();if(current.value().status()==SellBatchQuote.Status.REMOVING)quotes.put(tx,quote.id().toString(),copy(current.value(),SellBatchQuote.Status.RECOVERY_REQUIRED,current.value().executionKey(),current.value().recoveryPayloadBase64()),current.revision());return null;}).toCompletableFuture();}).toArray(CompletableFuture[]::new);return CompletableFuture.allOf(tasks).thenApply(ignored->pending.size());});}
    @Override public CompletionStage<SellReceipt>reconcile(UUID quoteId,boolean confirmed,String operationKey){return store.transact("advanced-sell-reconcile:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"advanced-sell-reconcile",operationKey))throw new IllegalStateException("DUPLICATE_RECONCILIATION");var current=quotes.get(tx,quoteId.toString()).orElseThrow();if(current.value().status()!=SellBatchQuote.Status.REMOVING&&current.value().status()!=SellBatchQuote.Status.RECOVERY_REQUIRED)throw new IllegalStateException("QUOTE_NOT_AMBIGUOUS");SellBatchQuote updated=copy(current.value(),confirmed?SellBatchQuote.Status.REMOVED:SellBatchQuote.Status.REJECTED,current.value().executionKey(),current.value().recoveryPayloadBase64());quotes.put(tx,quoteId.toString(),updated,current.revision());return updated;}).thenCompose(updated->confirmed?settle(updated):CompletableFuture.failedFuture(new IllegalStateException("REMOVAL_NOT_CONFIRMED")));}
    private CompletionStage<Optional<SellReceipt>>receiptForQuote(UUID quoteId){return store.read(reader->receiptByQuote(reader,quoteId));}
    private Optional<SellReceipt>receiptByQuote(com.magicstudios.magiccore.storage.DataReader reader,UUID quoteId)throws Exception{String after=null;while(true){var page=receipts.scanPage(reader,after,1000);var found=page.stream().map(RecordRepository.KeyedVersionedValue::value).filter(value->value.quoteId().equals(quoteId)).findFirst();if(found.isPresent())return found;if(page.size()<1000)return Optional.empty();after=page.getLast().key();}}
    private SellBatchQuote copy(SellBatchQuote q,SellBatchQuote.Status status,String execution,String payload){return new SellBatchQuote(q.id(),q.playerId(),q.scope(),q.category(),q.lines(),q.creditMinor(),status,execution,payload,q.createdAt(),q.expiresAt(),clock.instant());}
    private record Key(ItemFingerprint fingerprint,String itemId,String category,long unitWorth){}
}
