package com.magicstudios.magiccore.integrations.discord;

import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ConcurrentHashMap;

public final class PersistentCustomDiscordBridge implements CustomDiscordBridge {
    private static final char[] CODE_ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789".toCharArray();
    private final TransactionalDataStore store;private final Clock clock;private final byte[]secret;private final Duration codeTtl,messageMaximumAge;
    private final int maximumMessagesPerMinute,maximumRetryAttempts;private final Duration retryBase;private final SecureRandom random=new SecureRandom();
    private final RecordRepository<LinkCodeRecord>codes=new RecordRepository<>("discord.link-code",LinkCodeRecord.class);
    private final RecordRepository<DiscordLink>links=new RecordRepository<>("discord.link",DiscordLink.class);
    private final RecordRepository<DiscordIndex>discordIndex=new RecordRepository<>("discord.index",DiscordIndex.class);
    private final RecordRepository<BridgeOutboxMessage>outbox=new RecordRepository<>("discord.outbox",BridgeOutboxMessage.class);
    private final Map<String,RateWindow>rates=new ConcurrentHashMap<>();

    public PersistentCustomDiscordBridge(TransactionalDataStore store,Clock clock,byte[]secret,Duration codeTtl,Duration messageMaximumAge,int maximumMessagesPerMinute,int maximumRetryAttempts,Duration retryBase){if(secret.length<32)throw new IllegalArgumentException("Discord bridge secret must be at least 32 bytes");this.store=store;this.clock=clock;this.secret=secret.clone();this.codeTtl=codeTtl;this.messageMaximumAge=messageMaximumAge;this.maximumMessagesPerMinute=maximumMessagesPerMinute;this.maximumRetryAttempts=maximumRetryAttempts;this.retryBase=retryBase;}
    @Override public String provider(){return"CUSTOM_BOT";}@Override public boolean available(){return true;}
    @Override public CompletionStage<Optional<String>>linkedDiscordId(UUID playerId){return store.read(reader->links.get(reader,playerId.toString()).map(RecordRepository.VersionedValue::value).filter(DiscordLink::active).map(DiscordLink::discordId));}
    @Override public CompletionStage<DiscordLinkCodeIssue>issueLinkCode(UUID playerId,String operationKey){String code=code();String hash=hash(code);var now=clock.instant();LinkCodeRecord record=new LinkCodeRecord(hash,playerId,now.plus(codeTtl),false,now);return store.transact("discord-link-code:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"discord-link-code",operationKey))throw new IllegalStateException("DUPLICATE_LINK_CODE_REQUEST");var existing=links.get(tx,playerId.toString());if(existing.isPresent()&&existing.get().value().active())throw new IllegalStateException("DISCORD_ACCOUNT_ALREADY_LINKED");codes.put(tx,hash,record,0);return new DiscordLinkCodeIssue(playerId,code,record.expiresAt());});}
    @Override public CompletionStage<DiscordLink>redeemLinkCode(String code,String discordId,String operationKey){if(discordId==null||!discordId.matches("[0-9]{5,32}"))throw new IllegalArgumentException("Invalid Discord ID");String hash=hash(code.toUpperCase(java.util.Locale.ROOT));return store.transact("discord-link-redeem:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"discord-link-redeem",operationKey))throw new IllegalStateException("DUPLICATE_LINK_REDEMPTION");var codeRecord=codes.get(tx,hash).orElseThrow(()->new IllegalArgumentException("LINK_CODE_NOT_FOUND"));LinkCodeRecord current=codeRecord.value();if(current.used()||!current.expiresAt().isAfter(clock.instant()))throw new IllegalStateException("LINK_CODE_EXPIRED_OR_USED");var playerLink=links.get(tx,current.playerId().toString());if(playerLink.isPresent()&&playerLink.get().value().active())throw new IllegalStateException("PLAYER_ALREADY_LINKED");var discord=discordIndex.get(tx,discordId);if(discord.isPresent())throw new IllegalStateException("DISCORD_ACCOUNT_ALREADY_LINKED");DiscordLink link=new DiscordLink(current.playerId(),discordId,clock.instant(),null);links.put(tx,current.playerId().toString(),link,playerLink.map(RecordRepository.VersionedValue::revision).orElse(0L));discordIndex.put(tx,discordId,new DiscordIndex(discordId,current.playerId()),0);codes.put(tx,hash,new LinkCodeRecord(hash,current.playerId(),current.expiresAt(),true,current.createdAt()),codeRecord.revision());return link;});}
    @Override public CompletionStage<Boolean>unlink(UUID playerId,String operationKey){return store.transact("discord-unlink:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"discord-unlink",operationKey))return false;var current=links.get(tx,playerId.toString());if(current.isEmpty()||!current.get().value().active())return false;DiscordLink before=current.get().value();links.put(tx,playerId.toString(),new DiscordLink(playerId,before.discordId(),before.linkedAt(),clock.instant()),current.get().revision());var index=discordIndex.get(tx,before.discordId());if(index.isPresent())tx.delete("discord.index",before.discordId(),index.get().revision());return true;});}
    @Override public BridgeEnvelope sign(String type,String payload,String nonce){if(type==null||!type.matches("[A-Z][A-Z0-9_]*")||payload==null||payload.length()>65536||nonce==null||!nonce.matches("[A-Za-z0-9_-]{8,128}"))throw new IllegalArgumentException("Invalid bridge envelope");BridgeEnvelope unsigned=new BridgeEnvelope(UUID.randomUUID(),nonce,type,payload,clock.instant(),"");return new BridgeEnvelope(unsigned.id(),nonce,type,payload,unsigned.timestamp(),hmac(canonical(unsigned)));}
    @Override public CompletionStage<Boolean>accept(BridgeEnvelope envelope,String source){if(!rate(source))return CompletableFuture.failedFuture(new IllegalStateException("BRIDGE_RATE_LIMIT"));Instant now=clock.instant();if(envelope.timestamp().isBefore(now.minus(messageMaximumAge))||envelope.timestamp().isAfter(now.plusSeconds(5)))return CompletableFuture.failedFuture(new SecurityException("BRIDGE_MESSAGE_EXPIRED"));if(!MessageDigest.isEqual(hmac(canonical(envelope)).getBytes(StandardCharsets.US_ASCII),envelope.signature().getBytes(StandardCharsets.US_ASCII)))return CompletableFuture.failedFuture(new SecurityException("BRIDGE_SIGNATURE_INVALID"));return store.transact("discord-inbound:"+envelope.id(),tx->{if(!IdempotencyKeys.reserve(tx,"discord-bridge-nonce",envelope.nonce()))throw new SecurityException("BRIDGE_REPLAY");return true;});}
    @Override public CompletionStage<Boolean>notify(String message){BridgeEnvelope envelope=sign("NOTIFICATION",message,UUID.randomUUID().toString());BridgeOutboxMessage queued=new BridgeOutboxMessage(envelope.id(),envelope,BridgeOutboxMessage.Status.PENDING,0,"",clock.instant(),clock.instant(),clock.instant());return store.transact("discord-outbox:"+envelope.id(),tx->{outbox.put(tx,envelope.id().toString(),queued,0);return true;});}
    @Override public CompletionStage<List<BridgeOutboxMessage>>pendingOutbox(int limit){if(limit<1||limit>1000)throw new IllegalArgumentException("Outbox limit must be 1..1000");return store.read(reader->scanOutbox(reader).stream().filter(value->value.status()==BridgeOutboxMessage.Status.PENDING&&!value.nextAttemptAt().isAfter(clock.instant())).limit(limit).toList());}
    @Override public CompletionStage<Boolean>acknowledge(UUID messageId,String operationKey){return store.transact("discord-outbox-ack:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"discord-outbox-ack",operationKey))return false;var current=outbox.get(tx,messageId.toString());if(current.isEmpty()||current.get().value().status()!=BridgeOutboxMessage.Status.PENDING)return false;BridgeOutboxMessage before=current.get().value();outbox.put(tx,messageId.toString(),new BridgeOutboxMessage(before.id(),before.envelope(),BridgeOutboxMessage.Status.ACKNOWLEDGED,before.attempts(),before.lastError(),before.nextAttemptAt(),before.createdAt(),clock.instant()),current.get().revision());return true;});}
    @Override public CompletionStage<BridgeOutboxMessage>markFailed(UUID messageId,String error,String operationKey){return store.transact("discord-outbox-fail:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"discord-outbox-fail",operationKey))return outbox.get(tx,messageId.toString()).orElseThrow().value();var current=outbox.get(tx,messageId.toString()).orElseThrow(()->new IllegalArgumentException("OUTBOX_MESSAGE_NOT_FOUND"));BridgeOutboxMessage before=current.value();if(before.status()!=BridgeOutboxMessage.Status.PENDING)return before;int attempts=before.attempts()+1;BridgeOutboxMessage.Status status=attempts>=maximumRetryAttempts?BridgeOutboxMessage.Status.DEAD:BridgeOutboxMessage.Status.PENDING;long multiplier=1L<<Math.min(20,Math.max(0,attempts-1));Instant next=clock.instant().plus(retryBase.multipliedBy(multiplier));BridgeOutboxMessage updated=new BridgeOutboxMessage(before.id(),before.envelope(),status,attempts,sanitize(error),next,before.createdAt(),clock.instant());outbox.put(tx,messageId.toString(),updated,current.revision());return updated;});}
    @Override public CompletionStage<DiscordBridgeHealth>bridgeHealth(){return store.read(reader->{List<BridgeOutboxMessage>messages=scanOutbox(reader);return new DiscordBridgeHealth(true,messages.stream().filter(value->value.status()==BridgeOutboxMessage.Status.PENDING).count(),messages.stream().filter(value->value.status()==BridgeOutboxMessage.Status.DEAD).count(),clock.instant());});}
    private List<BridgeOutboxMessage>scanOutbox(com.magicstudios.magiccore.storage.DataReader reader)throws Exception{ArrayList<BridgeOutboxMessage>result=new ArrayList<>();String after=null;while(true){var page=outbox.scanPage(reader,after,1000);page.forEach(value->result.add(value.value()));if(page.size()<1000)break;after=page.getLast().key();}return result;}
    private boolean rate(String source){long minute=clock.instant().getEpochSecond()/60;RateWindow result=rates.compute(source,(key,current)->current==null||current.minute()!=minute?new RateWindow(minute,1):new RateWindow(minute,current.count()+1));return result.count()<=maximumMessagesPerMinute;}
    private String code(){StringBuilder value=new StringBuilder(8);for(int i=0;i<8;i++)value.append(CODE_ALPHABET[random.nextInt(CODE_ALPHABET.length)]);return value.toString();}
    private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception failure){throw new IllegalStateException(failure);}}
    private String hmac(String value){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret,"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception failure){throw new IllegalStateException(failure);}}
    private static String canonical(BridgeEnvelope value){return value.id()+"\n"+value.nonce()+"\n"+value.type()+"\n"+value.payload()+"\n"+value.timestamp().toEpochMilli();}
    private static String sanitize(String error){if(error==null)return"";return error.replaceAll("[\\r\\n]"," ").substring(0,Math.min(512,error.length()));}
    private record LinkCodeRecord(String codeHash,UUID playerId,Instant expiresAt,boolean used,Instant createdAt){}
    private record DiscordIndex(String discordId,UUID playerId){}
    private record RateWindow(long minute,int count){}
}
