package com.magicstudios.magiccore.modules.playerwarps;

import com.magicstudios.magiccore.capabilities.CapabilityService;
import com.magicstudios.magiccore.modules.economy.CurrencyDefinition;
import com.magicstudios.magiccore.modules.economy.EconomyTransactionSupport;
import com.magicstudios.magiccore.modules.essentials.WorldPosition;
import com.magicstudios.magiccore.protection.ProtectionAction;
import com.magicstudios.magiccore.protection.ProtectionService;
import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

public final class PersistentPlayerWarpService implements PlayerWarpService {
    private final TransactionalDataStore store;private final CapabilityService capabilities;private final ProtectionService protection;private final Clock clock;private final int maximumNameLength;
    private final Set<String>categories;private final Duration defaultExpiry;private final boolean sponsorshipEnabled;private final CurrencyDefinition sponsorshipCurrency;private final long sponsorshipPricePerHour;
    private final Duration sponsorshipMinimum,sponsorshipMaximum;private final int maximumActiveGlobal,maximumActivePerPlayer;
    private final RecordRepository<PlayerWarp>warps=new RecordRepository<>("playerwarps.warp",PlayerWarp.class);
    private final RecordRepository<FavoriteRecord>favorites=new RecordRepository<>("playerwarps.favorite",FavoriteRecord.class);
    private final RecordRepository<WarpSponsorship>sponsorships=new RecordRepository<>("playerwarps.sponsorship",WarpSponsorship.class);
    private final RecordRepository<WarpModeration>moderation=new RecordRepository<>("playerwarps.moderation",WarpModeration.class);

    public PersistentPlayerWarpService(TransactionalDataStore store,CapabilityService capabilities,ProtectionService protection,Clock clock,int maximumNameLength){this(store,capabilities,protection,clock,maximumNameLength,Set.of(),Duration.ZERO,false,null,0,Duration.ZERO,Duration.ZERO,1,1);}
    public PersistentPlayerWarpService(TransactionalDataStore store,CapabilityService capabilities,ProtectionService protection,Clock clock,int maximumNameLength,
                                       Set<String>categories,Duration defaultExpiry,boolean sponsorshipEnabled,CurrencyDefinition sponsorshipCurrency,long sponsorshipPricePerHour,
                                       Duration sponsorshipMinimum,Duration sponsorshipMaximum,int maximumActiveGlobal,int maximumActivePerPlayer){this.store=store;this.capabilities=capabilities;this.protection=protection;this.clock=clock;this.maximumNameLength=maximumNameLength;this.categories=categories.stream().map(value->value.toLowerCase(Locale.ROOT)).collect(java.util.stream.Collectors.toUnmodifiableSet());this.defaultExpiry=defaultExpiry;this.sponsorshipEnabled=sponsorshipEnabled;this.sponsorshipCurrency=sponsorshipCurrency;this.sponsorshipPricePerHour=sponsorshipPricePerHour;this.sponsorshipMinimum=sponsorshipMinimum;this.sponsorshipMaximum=sponsorshipMaximum;this.maximumActiveGlobal=maximumActiveGlobal;this.maximumActivePerPlayer=maximumActivePerPlayer;}

    @Override public CompletionStage<List<PlayerWarp>>activeWarps(){return store.read(reader->scanWarps(reader).stream().filter(value->value.activeAt(clock.instant())).sorted(Comparator.comparingLong(PlayerWarp::visits).reversed().thenComparing(PlayerWarp::id)).toList());}
    @Override public CompletionStage<List<PlayerWarp>>ownedBy(UUID ownerId){return store.read(reader->scanWarps(reader).stream().filter(value->value.ownerId().equals(ownerId)).sorted(Comparator.comparing(PlayerWarp::id)).toList());}
    @Override public CompletionStage<Optional<PlayerWarp>>findActive(String warpId){return store.read(reader->warps.get(reader,normalize(warpId)).map(RecordRepository.VersionedValue::value).filter(value->value.activeAt(clock.instant())));}
    @Override public CompletionStage<PlayerWarpMutation>create(UUID ownerId,String name,String category,WorldPosition position,String operationKey){String id=normalize(name),normalizedCategory=normalizeCategory(category);if(!categories.isEmpty()&&!categories.contains(normalizedCategory))throw new IllegalArgumentException("UNKNOWN_PLAYERWARP_CATEGORY");return protection.check(ownerId,position,ProtectionAction.CREATE_WARP).thenCompose(decision->{if(!decision.allowed())throw new IllegalStateException("PROTECTION_DENIED:"+decision.reason());return capabilities.limit(ownerId,"PLAYER_WARPS");}).thenCompose(limit->store.transact("playerwarp-create:"+operationKey,tx->{var current=warps.get(tx,id);if(!IdempotencyKeys.reserve(tx,"playerwarp-create",operationKey))return new PlayerWarpMutation(false,"REPLAY",current.map(RecordRepository.VersionedValue::value).orElse(null));if(current.isPresent())throw new IllegalStateException("WARP_ID_TAKEN");long count=scanWarps(tx).stream().filter(value->value.ownerId().equals(ownerId)).count();if(count>=limit)throw new IllegalStateException("PLAYER_WARP_LIMIT_REACHED");Instant now=clock.instant();PlayerWarp warp=new PlayerWarp(id,name,ownerId,position,normalizedCategory,PlayerWarp.Status.ACTIVE,0,now,now,defaultExpiry.isZero()?null:now.plus(defaultExpiry));warps.put(tx,id,warp,0);return new PlayerWarpMutation(true,"CREATED",warp);}));}
    @Override public CompletionStage<PlayerWarpMutation>delete(UUID ownerId,String warpId,String operationKey){String id=normalize(warpId);return store.transact("playerwarp-delete:"+operationKey,tx->{var current=warps.get(tx,id);if(!IdempotencyKeys.reserve(tx,"playerwarp-delete",operationKey))return new PlayerWarpMutation(false,"REPLAY",current.map(RecordRepository.VersionedValue::value).orElse(null));if(current.isEmpty())return new PlayerWarpMutation(false,"NOT_FOUND",null);if(!current.get().value().ownerId().equals(ownerId))throw new SecurityException("NOT_OWNER");if(scanSponsorships(tx).stream().anyMatch(value->value.warpId().equals(id)&&value.activeAt(clock.instant())))throw new IllegalStateException("CANCEL_ACTIVE_SPONSORSHIP_FIRST");tx.delete("playerwarps.warp",id,current.get().revision());return new PlayerWarpMutation(true,"DELETED",current.get().value());});}
    @Override public CompletionStage<Boolean>recordVisit(String warpId,UUID visitorId,String operationKey){String id=normalize(warpId);return store.transact("playerwarp-visit:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"playerwarp-visit",operationKey))return false;var current=warps.get(tx,id).orElseThrow(()->new IllegalStateException("WARP_NOT_FOUND"));if(!current.value().activeAt(clock.instant()))throw new IllegalStateException("WARP_UNAVAILABLE");PlayerWarp before=current.value();PlayerWarp updated=new PlayerWarp(before.id(),before.displayName(),before.ownerId(),before.position(),before.category(),before.status(),Math.addExact(before.visits(),1),before.createdAt(),clock.instant(),before.expiresAt());warps.put(tx,id,updated,current.revision());return true;});}
    @Override public CompletionStage<PlayerWarp>prepareVisit(String warpId,UUID visitorId,String operationKey){return findActive(warpId).thenCompose(found->{PlayerWarp warp=found.orElseThrow(()->new IllegalStateException("WARP_UNAVAILABLE"));return protection.check(visitorId,warp.position(),ProtectionAction.TELEPORT_IN).thenCompose(decision->{if(!decision.allowed())return CompletableFuture.failedFuture(new IllegalStateException("WARP_DESTINATION_UNSAFE:"+decision.reason()));return recordVisit(warp.id(),visitorId,operationKey).thenApply(ignored->warp);});});}
    @Override public CompletionStage<List<PlayerWarpView>>search(PlayerWarpQuery query){return store.read(reader->{Instant now=clock.instant();Set<String>viewerFavorites=new HashSet<>();if(query.viewerId()!=null)scanFavorites(reader).stream().filter(value->value.playerId().equals(query.viewerId())).forEach(value->viewerFavorites.add(value.warpId()));Map<String,WarpSponsorship>promoted=new HashMap<>();scanSponsorships(reader).stream().filter(value->value.activeAt(now)).sorted(Comparator.comparing(WarpSponsorship::startsAt).thenComparing(value->value.id().toString())).forEach(value->promoted.putIfAbsent(value.warpId(),value));String text=query.text().toLowerCase(Locale.ROOT);List<PlayerWarpView>views=scanWarps(reader).stream().filter(value->value.activeAt(now)).filter(value->query.category().isBlank()||value.category().equalsIgnoreCase(query.category())).filter(value->query.ownerId()==null||value.ownerId().equals(query.ownerId())).filter(value->text.isBlank()||value.id().contains(text)||value.displayName().toLowerCase(Locale.ROOT).contains(text)).map(value->{WarpSponsorship sponsor=promoted.get(value.id());return new PlayerWarpView(value,viewerFavorites.contains(value.id()),sponsor!=null,sponsor==null?null:sponsor.endsAt());}).sorted(comparator(query.sort())).skip(query.offset()).limit(query.limit()).toList();return views;});}
    @Override public CompletionStage<Boolean>favorite(UUID playerId,String warpId,boolean favorite,String operationKey){String id=normalize(warpId),key=playerId+":"+id;return store.transact("playerwarp-favorite:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"playerwarp-favorite",operationKey))return false;if(warps.get(tx,id).isEmpty())throw new IllegalArgumentException("WARP_NOT_FOUND");var current=favorites.get(tx,key);if(favorite){if(current.isPresent())return false;favorites.put(tx,key,new FavoriteRecord(playerId,id,clock.instant()),0);return true;}if(current.isEmpty())return false;tx.delete("playerwarps.favorite",key,current.get().revision());return true;});}
    @Override public CompletionStage<PlayerWarpMutation>moderate(UUID actorId,String warpId,PlayerWarp.Status status,String reason,String operationKey){if(status==null||reason==null||reason.isBlank())throw new IllegalArgumentException("Moderation status and reason are required");String id=normalize(warpId);return capabilities.has(actorId,"PLAYERWARPS_MODERATE").thenCompose(allowed->{if(!allowed)return CompletableFuture.failedFuture(new SecurityException("PLAYERWARP_MODERATION_DENIED"));return store.transact("playerwarp-moderate:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"playerwarp-moderate",operationKey))return new PlayerWarpMutation(false,"REPLAY",warps.get(tx,id).map(RecordRepository.VersionedValue::value).orElse(null));var current=warps.get(tx,id).orElseThrow(()->new IllegalArgumentException("WARP_NOT_FOUND"));PlayerWarp before=current.value();PlayerWarp updated=new PlayerWarp(before.id(),before.displayName(),before.ownerId(),before.position(),before.category(),status,before.visits(),before.createdAt(),clock.instant(),before.expiresAt());warps.put(tx,id,updated,current.revision());moderation.put(tx,operationKey,new WarpModeration(id,actorId,status,reason,clock.instant()),0);return new PlayerWarpMutation(true,"MODERATED",updated);});});}
    @Override public CompletionStage<PlayerWarpMutation>transfer(UUID ownerId,String warpId,UUID newOwnerId,String operationKey){String id=normalize(warpId);return capabilities.limit(newOwnerId,"PLAYER_WARPS").thenCompose(limit->store.transact("playerwarp-transfer:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"playerwarp-transfer",operationKey))return new PlayerWarpMutation(false,"REPLAY",warps.get(tx,id).map(RecordRepository.VersionedValue::value).orElse(null));var current=warps.get(tx,id).orElseThrow(()->new IllegalArgumentException("WARP_NOT_FOUND"));if(!current.value().ownerId().equals(ownerId))throw new SecurityException("NOT_OWNER");long owned=scanWarps(tx).stream().filter(value->value.ownerId().equals(newOwnerId)).count();if(owned>=limit)throw new IllegalStateException("NEW_OWNER_WARP_LIMIT");PlayerWarp before=current.value();PlayerWarp updated=new PlayerWarp(before.id(),before.displayName(),newOwnerId,before.position(),before.category(),before.status(),before.visits(),before.createdAt(),clock.instant(),before.expiresAt());warps.put(tx,id,updated,current.revision());return new PlayerWarpMutation(true,"TRANSFERRED",updated);}));}
    @Override public CompletionStage<WarpSponsorship>sponsor(UUID playerId,String warpId,Duration duration,String operationKey){if(!sponsorshipEnabled)throw new IllegalStateException("WARP_SPONSORSHIP_DISABLED");if(duration.compareTo(sponsorshipMinimum)<0||duration.compareTo(sponsorshipMaximum)>0)throw new IllegalArgumentException("SPONSORSHIP_DURATION_OUT_OF_BOUNDS");String id=normalize(warpId);long hours=Math.floorDiv(Math.addExact(duration.toSeconds(),3599),3600);long price=Math.multiplyExact(hours,sponsorshipPricePerHour);return store.transact("playerwarp-sponsor:"+operationKey,tx->{var replay=scanSponsorships(tx).stream().filter(value->value.id().toString().equals(operationKey)).findFirst();if(!IdempotencyKeys.reserve(tx,"playerwarp-sponsor",operationKey))throw new IllegalStateException("DUPLICATE_SPONSORSHIP");var warp=warps.get(tx,id).orElseThrow(()->new IllegalArgumentException("WARP_NOT_FOUND")).value();if(!warp.ownerId().equals(playerId))throw new SecurityException("ONLY_OWNER_CAN_SPONSOR");if(!warp.activeAt(clock.instant()))throw new IllegalStateException("WARP_UNAVAILABLE");List<WarpSponsorship>active=scanSponsorships(tx).stream().filter(value->value.activeAt(clock.instant())).toList();if(active.size()>=maximumActiveGlobal||active.stream().filter(value->value.sponsorId().equals(playerId)).count()>=maximumActivePerPlayer)throw new IllegalStateException("SPONSORSHIP_CAP_REACHED");if(active.stream().anyMatch(value->value.warpId().equals(id)))throw new IllegalStateException("WARP_ALREADY_SPONSORED");EconomyTransactionSupport.credit(tx,playerId,sponsorshipCurrency,-price,operationKey,playerId.toString(),"playerwarp-sponsorship:"+id,clock.instant());Instant now=clock.instant();WarpSponsorship sponsorship=new WarpSponsorship(UUID.randomUUID(),id,playerId,sponsorshipCurrency.id(),price,0,now,now.plus(duration),WarpSponsorship.Status.ACTIVE,now);sponsorships.put(tx,sponsorship.id().toString(),sponsorship,0);return sponsorship;});}
    @Override public CompletionStage<WarpSponsorship>cancelSponsorship(UUID playerId,UUID sponsorshipId,String operationKey){return store.transact("playerwarp-sponsor-cancel:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"playerwarp-sponsor-cancel",operationKey))return sponsorships.get(tx,sponsorshipId.toString()).orElseThrow().value();var current=sponsorships.get(tx,sponsorshipId.toString()).orElseThrow(()->new IllegalArgumentException("SPONSORSHIP_NOT_FOUND"));WarpSponsorship before=current.value();if(!before.sponsorId().equals(playerId))throw new SecurityException("NOT_SPONSOR");if(before.status()!=WarpSponsorship.Status.ACTIVE)throw new IllegalStateException("SPONSORSHIP_NOT_ACTIVE");long total=Math.max(1,Duration.between(before.startsAt(),before.endsAt()).toSeconds()),remaining=Math.max(0,Duration.between(clock.instant(),before.endsAt()).toSeconds());long refund=Math.floorDiv(Math.multiplyExact(before.chargedMinor(),remaining),total);if(refund>0)EconomyTransactionSupport.credit(tx,playerId,sponsorshipCurrency,refund,operationKey,playerId.toString(),"playerwarp-sponsorship-refund:"+before.warpId(),clock.instant());WarpSponsorship cancelled=new WarpSponsorship(before.id(),before.warpId(),before.sponsorId(),before.currency(),before.chargedMinor(),refund,before.startsAt(),before.endsAt(),WarpSponsorship.Status.CANCELLED,clock.instant());sponsorships.put(tx,before.id().toString(),cancelled,current.revision());return cancelled;});}
    @Override public CompletionStage<Integer>expireSponsorships(){return store.transact("playerwarp-sponsor-expire:"+clock.instant().getEpochSecond(),tx->{int count=0;for(WarpSponsorship before:scanSponsorships(tx)){if(before.status()!=WarpSponsorship.Status.ACTIVE||before.endsAt().isAfter(clock.instant()))continue;var current=sponsorships.get(tx,before.id().toString()).orElseThrow();WarpSponsorship expired=new WarpSponsorship(before.id(),before.warpId(),before.sponsorId(),before.currency(),before.chargedMinor(),before.refundedMinor(),before.startsAt(),before.endsAt(),WarpSponsorship.Status.EXPIRED,clock.instant());sponsorships.put(tx,before.id().toString(),expired,current.revision());count++;}return count;});}

    private Comparator<PlayerWarpView>comparator(PlayerWarpQuery.Sort sort){Comparator<PlayerWarpView>promoted=Comparator.comparing(PlayerWarpView::promoted).reversed().thenComparing(value->value.promotionEndsAt()==null?Instant.MAX:value.promotionEndsAt()).thenComparing(value->value.warp().id());return switch(sort){case SPONSORED->promoted;case VISITS->Comparator.comparingLong((PlayerWarpView value)->value.warp().visits()).reversed().thenComparing(value->value.warp().id());case NEWEST->Comparator.comparing((PlayerWarpView value)->value.warp().createdAt()).reversed().thenComparing(value->value.warp().id());case NAME->Comparator.comparing((PlayerWarpView value)->value.warp().displayName().toLowerCase(Locale.ROOT)).thenComparing(value->value.warp().id());case FAVORITES->Comparator.comparing((PlayerWarpView value)->value.favorite()).reversed().thenComparing(promoted);};}
    private List<PlayerWarp>scanWarps(com.magicstudios.magiccore.storage.DataReader reader)throws Exception{return scan(reader,warps).stream().map(RecordRepository.KeyedVersionedValue::value).toList();}
    private List<FavoriteRecord>scanFavorites(com.magicstudios.magiccore.storage.DataReader reader)throws Exception{return scan(reader,favorites).stream().map(RecordRepository.KeyedVersionedValue::value).toList();}
    private List<WarpSponsorship>scanSponsorships(com.magicstudios.magiccore.storage.DataReader reader)throws Exception{return scan(reader,sponsorships).stream().map(RecordRepository.KeyedVersionedValue::value).toList();}
    private static<T>List<RecordRepository.KeyedVersionedValue<T>>scan(com.magicstudios.magiccore.storage.DataReader reader,RecordRepository<T>repository)throws Exception{ArrayList<RecordRepository.KeyedVersionedValue<T>>result=new ArrayList<>();String after=null;while(true){var page=repository.scanPage(reader,after,1000);result.addAll(page);if(page.size()<1000)break;after=page.getLast().key();}return result;}
    private String normalize(String name){if(name==null||!name.matches("[A-Za-z0-9_-]{1,"+maximumNameLength+"}"))throw new IllegalArgumentException("Warp name must contain 1.."+maximumNameLength+" safe characters");return name.toLowerCase(Locale.ROOT);}
    private static String normalizeCategory(String category){if(category==null||!category.matches("[A-Za-z0-9_-]{1,24}"))throw new IllegalArgumentException("Invalid category");return category.toLowerCase(Locale.ROOT);}
    private record FavoriteRecord(UUID playerId,String warpId,Instant createdAt){}
    private record WarpModeration(String warpId,UUID actorId,PlayerWarp.Status status,String reason,Instant occurredAt){}
}
