package com.magicstudios.magiccore.modules.billford;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.magicstudios.magiccore.audit.*;import com.magicstudios.magiccore.delivery.*;import com.magicstudios.magiccore.modules.economy.*;import com.magicstudios.magiccore.modules.shop.*;import com.magicstudios.magiccore.storage.*;
import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.function.Function;import java.util.stream.Collectors;

public final class PersistentBillfordService implements BillfordService{
 private static final ObjectMapper JSON=new ObjectMapper();private final TransactionalDataStore store;private final BatchInventoryRemovalPort inventory;private final Map<String,BillfordRecipe>recipes;private final Map<String,CurrencyDefinition>currencies;private final AuditService audit;private final Clock clock;
 private final RecordRepository<BillfordStock>stocks=new RecordRepository<>("billford.stock",BillfordStock.class);private final RecordRepository<BillfordPlayerState>players=new RecordRepository<>("billford.player",BillfordPlayerState.class);private final RecordRepository<BillfordExchange>exchanges=new RecordRepository<>("billford.exchange",BillfordExchange.class);
 public PersistentBillfordService(TransactionalDataStore store,BatchInventoryRemovalPort inventory,List<BillfordRecipe>recipes,Map<String,CurrencyDefinition>currencies,AuditService audit,Clock clock){this.store=store;this.inventory=inventory;this.recipes=recipes.stream().collect(Collectors.toUnmodifiableMap(BillfordRecipe::id,Function.identity()));this.currencies=Map.copyOf(currencies);this.audit=audit;this.clock=clock;}
 @Override public List<BillfordRecipe>recipes(){return recipes.values().stream().sorted(Comparator.comparing(BillfordRecipe::id)).toList();}
 @Override public CompletionStage<BillfordPreview>preview(UUID player,String id){BillfordRecipe recipe=require(id);return store.read(reader->{BillfordStock stock=stock(reader,recipe);BillfordPlayerState state=player(reader,player,recipe);String code=stock.remaining()<1?"OUT_OF_STOCK":state.claims()>=recipe.perPlayerLimit()?"PLAYER_LIMIT":state.cooldownUntil().isAfter(clock.instant())?"COOLDOWN":"ELIGIBLE";return new BillfordPreview(recipe,stock.remaining(),state.claims(),state.cooldownUntil(),code.equals("ELIGIBLE"),code,recipe.rewards());});}
 @Override public CompletionStage<BillfordExchange>exchange(UUID playerId,String recipeId,List<BillfordCandidate>snapshot,String operationKey){BillfordRecipe recipe=require(recipeId);List<BatchInventoryRemovalPort.RemovalLine>removals=plan(recipe,snapshot);UUID exchangeId=UUID.randomUUID();return reserve(exchangeId,playerId,recipe,removals,operationKey).thenCompose(exchange->inventory.removeBatchExact(playerId,removals,operationKey).thenCompose(receipt->receipt.removed()?markRemoved(exchange,receipt.recoveryPayloadBase64()).thenCompose(this::settle):rollback(exchange,receipt.code()).thenCompose(ignored->CompletableFuture.failedFuture(new IllegalStateException(receipt.code())))));}
 private CompletionStage<BillfordExchange>reserve(UUID id,UUID playerId,BillfordRecipe recipe,List<BatchInventoryRemovalPort.RemovalLine>removals,String operationKey){return store.transact("billford-reserve:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"billford-exchange",operationKey))throw new IllegalStateException("DUPLICATE_EXCHANGE");var stockRecord=stocks.get(tx,recipe.id());BillfordStock stock=stockRecord.map(RecordRepository.VersionedValue::value).orElse(new BillfordStock(recipe.id(),recipe.stock(),clock.instant()));if(stock.remaining()<1)throw new IllegalStateException("OUT_OF_STOCK");String playerKey=key(playerId,recipe.id());var playerRecord=players.get(tx,playerKey);BillfordPlayerState state=playerRecord.map(RecordRepository.VersionedValue::value).orElse(new BillfordPlayerState(playerId,recipe.id(),0,Instant.EPOCH,clock.instant()));if(state.claims()>=recipe.perPlayerLimit())throw new IllegalStateException("PLAYER_LIMIT");if(state.cooldownUntil().isAfter(clock.instant()))throw new IllegalStateException("COOLDOWN");BillfordReward reward=choose(id,recipe.rewards());stocks.put(tx,recipe.id(),new BillfordStock(recipe.id(),stock.remaining()-1,clock.instant()),stockRecord.map(RecordRepository.VersionedValue::revision).orElse(0L));players.put(tx,playerKey,new BillfordPlayerState(playerId,recipe.id(),state.claims()+1,clock.instant().plus(recipe.cooldown()),clock.instant()),playerRecord.map(RecordRepository.VersionedValue::revision).orElse(0L));BillfordExchange exchange=new BillfordExchange(id,playerId,recipe.id(),removals,reward,BillfordExchange.Status.RESERVED,operationKey,"",clock.instant(),clock.instant());exchanges.put(tx,id.toString(),exchange,0);return exchange;});}
 private CompletionStage<BillfordExchange>markRemoved(BillfordExchange exchange,String payload){return mutate(exchange.id(),"billford-removed:"+exchange.operationKey(),current->{if(current.status()!=BillfordExchange.Status.RESERVED)throw new IllegalStateException("EXCHANGE_STATE_CONFLICT");return copy(current,BillfordExchange.Status.REMOVED,payload);});}
 private CompletionStage<BillfordExchange>settle(BillfordExchange exchange){return store.transact("billford-settle:"+exchange.operationKey(),tx->{var current=exchanges.get(tx,exchange.id().toString()).orElseThrow();if(current.value().status()==BillfordExchange.Status.SETTLED)return current.value();if(current.value().status()!=BillfordExchange.Status.REMOVED)throw new IllegalStateException("EXCHANGE_NOT_REMOVED");BillfordReward reward=current.value().reward();if(reward.type()==BillfordReward.Type.CURRENCY)EconomyTransactionSupport.credit(tx,exchange.playerId(),currencies.get(reward.currency()),reward.amountMinor(),exchange.operationKey(),"BILLFORD","billford:"+exchange.recipeId(),clock.instant());else{var payload=new com.magicstudios.magiccore.modules.shop.InternalShopService.PurchasePayload(reward.id(),reward.material(),reward.amount(),reward.itemDataBase64());MailboxDelivery delivery=MailboxDelivery.pending(UUID.randomUUID(),exchange.playerId(),exchange.operationKey(),"magiccore/shop-purchase-v1",JSON.writeValueAsBytes(payload),clock.instant());DeliveryTransactionSupport.enqueue(tx,delivery);}BillfordExchange settled=copy(current.value(),BillfordExchange.Status.SETTLED,current.value().recoveryPayloadBase64());exchanges.put(tx,exchange.id().toString(),settled,current.revision());return settled;}).thenCompose(settled->audit.record(new AuditEvent(UUID.randomUUID(),settled.operationKey(),"BILLFORD_EXCHANGE",settled.playerId().toString(),settled.recipeId(),Map.of(),Map.of("reward",settled.reward().id(),"exchange",settled.id().toString()),"MagicCore:Billford",clock.instant())).thenApply(ignored->settled));}
 private CompletionStage<BillfordExchange>rollback(BillfordExchange exchange,String reason){BillfordRecipe recipe=require(exchange.recipeId());return store.transact("billford-rollback:"+exchange.operationKey(),tx->{var current=exchanges.get(tx,exchange.id().toString()).orElseThrow();if(current.value().status()!=BillfordExchange.Status.RESERVED)return current.value();var stockRecord=stocks.get(tx,recipe.id()).orElseThrow();stocks.put(tx,recipe.id(),new BillfordStock(recipe.id(),stockRecord.value().remaining()+1,clock.instant()),stockRecord.revision());String pk=key(exchange.playerId(),recipe.id());var state=players.get(tx,pk).orElseThrow();players.put(tx,pk,new BillfordPlayerState(exchange.playerId(),recipe.id(),Math.max(0,state.value().claims()-1),Instant.EPOCH,clock.instant()),state.revision());BillfordExchange rejected=copy(current.value(),BillfordExchange.Status.REJECTED,reason);exchanges.put(tx,exchange.id().toString(),rejected,current.revision());return rejected;});}
 @Override public CompletionStage<Optional<BillfordExchange>>find(UUID id){return store.read(reader->exchanges.get(reader,id.toString()).map(RecordRepository.VersionedValue::value));}
 @Override public CompletionStage<Integer>recover(){return store.read(reader->{List<BillfordExchange>pending=new ArrayList<>();String after=null;while(true){var page=exchanges.scanPage(reader,after,1000);page.stream().map(RecordRepository.KeyedVersionedValue::value).filter(value->value.status()==BillfordExchange.Status.REMOVED||value.status()==BillfordExchange.Status.RESERVED).forEach(pending::add);if(page.size()<1000)break;after=page.getLast().key();}return pending;}).thenCompose(pending->{CompletableFuture<?>[]tasks=pending.stream().map(value->value.status()==BillfordExchange.Status.REMOVED?settle(value).toCompletableFuture():mutate(value.id(),"billford-recovery:"+value.id(),current->copy(current,BillfordExchange.Status.RECOVERY_REQUIRED,current.recoveryPayloadBase64())).toCompletableFuture()).toArray(CompletableFuture[]::new);return CompletableFuture.allOf(tasks).thenApply(ignored->pending.size());});}
 @Override public CompletionStage<BillfordExchange>reconcile(UUID id,boolean confirmed,String operationKey){return store.transact("billford-reconcile:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"billford-reconcile",operationKey))throw new IllegalStateException("DUPLICATE_RECONCILIATION");var current=exchanges.get(tx,id.toString()).orElseThrow();if(current.value().status()!=BillfordExchange.Status.RECOVERY_REQUIRED)throw new IllegalStateException("EXCHANGE_NOT_AMBIGUOUS");BillfordExchange updated=copy(current.value(),confirmed?BillfordExchange.Status.REMOVED:BillfordExchange.Status.RESERVED,current.value().recoveryPayloadBase64());exchanges.put(tx,id.toString(),updated,current.revision());return updated;}).thenCompose(value->confirmed?settle(value):rollback(value,"REMOVAL_NOT_CONFIRMED"));}
 private CompletionStage<BillfordExchange>mutate(UUID id,String txId,java.util.function.UnaryOperator<BillfordExchange>change){return store.transact(txId,tx->{var current=exchanges.get(tx,id.toString()).orElseThrow();BillfordExchange updated=change.apply(current.value());exchanges.put(tx,id.toString(),updated,current.revision());return updated;});}
 private List<BatchInventoryRemovalPort.RemovalLine>plan(BillfordRecipe recipe,List<BillfordCandidate>snapshot){List<BatchInventoryRemovalPort.RemovalLine>result=new ArrayList<>();for(BillfordIngredient ingredient:recipe.ingredients()){int remaining=ingredient.amount();for(BillfordCandidate candidate:snapshot){if(candidate.protectedItem()||!candidate.itemId().equalsIgnoreCase(ingredient.itemId())||remaining==0)continue;int take=Math.min(remaining,candidate.amount());result.add(new BatchInventoryRemovalPort.RemovalLine(candidate.fingerprint(),take));remaining-=take;}if(remaining>0)throw new IllegalArgumentException("MISSING_INGREDIENT:"+ingredient.itemId());}Map<com.magicstudios.magiccore.modules.shop.ItemFingerprint,Integer>grouped=new LinkedHashMap<>();result.forEach(line->grouped.merge(line.fingerprint(),line.quantity(),Math::addExact));return grouped.entrySet().stream().map(entry->new BatchInventoryRemovalPort.RemovalLine(entry.getKey(),entry.getValue())).toList();}
 private BillfordStock stock(DataReader reader,BillfordRecipe recipe)throws Exception{return stocks.get(reader,recipe.id()).map(RecordRepository.VersionedValue::value).orElse(new BillfordStock(recipe.id(),recipe.stock(),clock.instant()));}private BillfordPlayerState player(DataReader reader,UUID player,BillfordRecipe recipe)throws Exception{return players.get(reader,key(player,recipe.id())).map(RecordRepository.VersionedValue::value).orElse(new BillfordPlayerState(player,recipe.id(),0,Instant.EPOCH,clock.instant()));}
 private BillfordRecipe require(String id){BillfordRecipe value=recipes.get(id.toLowerCase(Locale.ROOT));if(value==null)throw new IllegalArgumentException("UNKNOWN_RECIPE");return value;}private static String key(UUID player,String recipe){return player+":"+recipe;}private BillfordExchange copy(BillfordExchange value,BillfordExchange.Status status,String payload){return new BillfordExchange(value.id(),value.playerId(),value.recipeId(),value.removals(),value.reward(),status,value.operationKey(),payload,value.createdAt(),clock.instant());}
 private static BillfordReward choose(UUID id,List<BillfordReward>rewards){int total=rewards.stream().mapToInt(BillfordReward::weight).sum();int selected=Math.floorMod(id.hashCode(),total);for(BillfordReward reward:rewards){selected-=reward.weight();if(selected<0)return reward;}return rewards.getLast();}
}
