package com.magicstudios.magiccore.phaseseven;

import com.magicstudios.magiccore.api.DomainEventBus;
import com.magicstudios.magiccore.config.model.EventsFile;
import com.magicstudios.magiccore.modules.economy.*;
import com.magicstudios.magiccore.modules.events.*;
import com.magicstudios.magiccore.platform.BoundedIoExecutor;
import com.magicstudios.magiccore.storage.InMemoryTransactionalDataStore;
import org.junit.jupiter.api.Test;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class EventServicesTest {
    @Test void kothResetsWhenContestedAndRewardsOneAuthoritativeTeamOnce(){try(var store=new InMemoryTransactionalDataStore(new BoundedIoExecutor(2,64,"koth-test"))){Clock clock=Clock.fixed(Instant.parse("2026-08-11T12:00:00Z"),ZoneOffset.UTC);CurrencyDefinition coins=coins();var service=new PersistentKothService(store,clock,new DomainEventBus(),List.of(new KothDefinition("HILL","Hill","world",0,0,0,10,100,10,Duration.ofSeconds(3),Duration.ZERO,Duration.ofHours(1),Set.of("ELYTRA"),new EventsFile.EventReward("COINS",500))),Map.of("COINS",coins));UUID first=UUID.randomUUID(),second=UUID.randomUUID(),team=UUID.randomUUID();KothRun run=service.start("HILL","start").toCompletableFuture().join();KothContender contender=new KothContender(team.toString(),"Blue",Set.of(first,second));assertThat(service.sample(run.id(),List.of(contender),Duration.ofSeconds(1),"tick-1").toCompletableFuture().join().capturedMillis()).isEqualTo(1000);assertThat(service.sample(run.id(),List.of(contender,new KothContender(UUID.randomUUID().toString(),"Red",Set.of(UUID.randomUUID()))),Duration.ofSeconds(1),"contested").toCompletableFuture().join().capturedMillis()).isZero();service.sample(run.id(),List.of(contender),Duration.ofSeconds(2),"tick-2").toCompletableFuture().join();KothRun won=service.sample(run.id(),List.of(contender),Duration.ofSeconds(1),"tick-3").toCompletableFuture().join();assertThat(won.status()).isEqualTo(KothRun.Status.COMPLETED);var economy=new PersistentEconomyService(store,new DomainEventBus(),"COINS",Map.of("COINS",coins),clock);assertThat(economy.balance(first,"COINS").toCompletableFuture().join().minorUnits()).isEqualTo(500);assertThat(economy.balance(second,"COINS").toCompletableFuture().join().minorUnits()).isEqualTo(500);assertThat(service.sample(run.id(),List.of(contender),Duration.ofSeconds(1),"after-win").toCompletableFuture().join().status()).isEqualTo(KothRun.Status.COMPLETED);}}

    @Test void verifiedOfflineVotesAreIdempotentAndPinataLimitsAreTransactional(){try(var store=new InMemoryTransactionalDataStore(new BoundedIoExecutor(2,64,"vote-party-test"))){Clock clock=Clock.fixed(Instant.parse("2026-08-11T12:00:00Z"),ZoneOffset.UTC);CurrencyDefinition coins=coins();EventsFile.Pinata pinata=new EventsFile.Pinata("world",0,64,0,"LLAMA",2,1,new EventsFile.EventReward("COINS",10),new EventsFile.EventReward("COINS",50),"<gold>Pinata");EventsFile.VoteParty policy=new EventsFile.VoteParty(true,2,"COUNT_AND_REWARD",true,pinata);var service=new PersistentVotePartyService(store,clock,new DomainEventBus(),policy,Map.of("COINS",coins));UUID offline=UUID.randomUUID(),online=UUID.randomUUID();VotePartyOutcome first=service.recordVerifiedVote("provider-1",offline,"site",clock.instant(),false).toCompletableFuture().join();assertThat(first.state().count()).isEqualTo(1);assertThat(service.recordVerifiedVote("provider-1",offline,"site",clock.instant(),false).toCompletableFuture().join().state().count()).isEqualTo(1);PinataParty pending=service.recordVerifiedVote("provider-2",online,"site",clock.instant(),true).toCompletableFuture().join().triggeredParty().orElseThrow();PinataParty active=service.activate(pending.id(),"activate").toCompletableFuture().join();assertThat(service.hit(active.id(),offline,"hit-offline-voter").toCompletableFuture().join().totalHits()).isEqualTo(1);assertThatThrownBy(()->service.hit(active.id(),offline,"hit-limit").toCompletableFuture().join()).hasRootCauseMessage("PINATA_PLAYER_HIT_LIMIT");PinataParty complete=service.hit(active.id(),online,"hit-final").toCompletableFuture().join();assertThat(complete.status()).isEqualTo(PinataParty.Status.COMPLETED);var economy=new PersistentEconomyService(store,new DomainEventBus(),"COINS",Map.of("COINS",coins),clock);assertThat(economy.balance(offline,"COINS").toCompletableFuture().join().minorUnits()).isEqualTo(10);assertThat(economy.balance(online,"COINS").toCompletableFuture().join().minorUnits()).isEqualTo(60);}}
    private static CurrencyDefinition coins(){return new CurrencyDefinition("COINS","Coins","$",0,0,1_000_000);}
}
