package com.magicstudios.magiccore.modules.events;

import com.magicstudios.magiccore.api.DomainEventBus;
import com.magicstudios.magiccore.config.model.EventsFile;
import com.magicstudios.magiccore.modules.economy.CurrencyDefinition;
import com.magicstudios.magiccore.modules.economy.EconomyTransactionSupport;
import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.atomic.AtomicReference;

public final class PersistentVotePartyService implements VotePartyService {
    private static final String STATE="global";private final TransactionalDataStore store;private final Clock clock;private final DomainEventBus events;private final EventsFile.VoteParty policy;private final Map<String,CurrencyDefinition>currencies;
    private final RecordRepository<VerifiedVote>votes=new RecordRepository<>("events.vote",VerifiedVote.class);private final RecordRepository<VotePartyState>states=new RecordRepository<>("events.vote.state",VotePartyState.class);private final RecordRepository<PinataParty>parties=new RecordRepository<>("events.pinata",PinataParty.class);
    public PersistentVotePartyService(TransactionalDataStore store,Clock clock,DomainEventBus events,EventsFile.VoteParty policy,Map<String,CurrencyDefinition>currencies){this.store=store;this.clock=clock;this.events=events;this.policy=policy;this.currencies=Map.copyOf(currencies);}
    @Override public CompletionStage<VotePartyOutcome>recordVerifiedVote(String providerEventId,UUID playerId,String service,Instant occurredAt,boolean online){if(providerEventId==null||providerEventId.isBlank()||providerEventId.length()>200)throw new IllegalArgumentException("Provider vote event ID is invalid");if(occurredAt.isAfter(clock.instant().plusSeconds(300))||occurredAt.isBefore(clock.instant().minusSeconds(86400)))throw new IllegalArgumentException("Verified vote timestamp is outside the accepted window");String key=UUID.nameUUIDFromBytes(providerEventId.getBytes(StandardCharsets.UTF_8)).toString();AtomicReference<VoteVerified>event=new AtomicReference<>();return store.transact("verified-vote:"+key,tx->{var duplicate=votes.get(tx,key);if(duplicate.isPresent()){VerifiedVote vote=duplicate.get().value();VotePartyState state=states.get(tx,STATE).map(RecordRepository.VersionedValue::value).orElse(VotePartyState.initial(clock.instant()));return new VotePartyOutcome(vote,state,Optional.empty());}boolean counted=online||!policy.offlinePolicy().equals("IGNORE");boolean eligible=online||policy.offlinePolicy().equals("COUNT_AND_REWARD");VerifiedVote vote=new VerifiedVote(UUID.randomUUID(),providerEventId,playerId,service,online,counted,eligible,occurredAt);votes.put(tx,key,vote,0);var current=states.get(tx,STATE);VotePartyState state=current.map(RecordRepository.VersionedValue::value).orElse(VotePartyState.initial(clock.instant()));Optional<PinataParty>triggered=Optional.empty();if(counted){Set<UUID>voters=new LinkedHashSet<>(state.eligibleVoters());if(eligible)voters.add(playerId);int count=state.count()+1;if(count>=policy.threshold()){PinataParty party=new PinataParty(state.cycleId(),PinataParty.Status.PENDING,policy.pinata().maximumHits(),0,Map.of(),voters,null,clock.instant(),null,null);parties.put(tx,party.id().toString(),party,0);triggered=Optional.of(party);state=VotePartyState.initial(clock.instant());}else state=new VotePartyState(state.cycleId(),count,voters,clock.instant());states.put(tx,STATE,state,current.map(RecordRepository.VersionedValue::revision).orElse(0L));}event.set(new VoteVerified(vote.id(),playerId,service,counted,triggered.isPresent(),clock.instant()));return new VotePartyOutcome(vote,state,triggered);}).thenApply(outcome->{if(event.get()!=null)events.publish(event.get());return outcome;});}
    @Override public CompletionStage<VotePartyState>state(){return store.read(reader->states.get(reader,STATE).map(RecordRepository.VersionedValue::value).orElse(VotePartyState.initial(clock.instant())));}
    @Override public CompletionStage<Optional<PinataParty>>activeParty(){return store.read(reader->scan(reader).stream().filter(value->value.status()==PinataParty.Status.ACTIVE).min(Comparator.comparing(PinataParty::createdAt)));}
    @Override public CompletionStage<List<PinataParty>>pendingParties(int limit){if(limit<1||limit>100)throw new IllegalArgumentException("Pinata queue limit must be 1..100");return store.read(reader->scan(reader).stream().filter(value->value.status()==PinataParty.Status.PENDING).sorted(Comparator.comparing(PinataParty::createdAt)).limit(limit).toList());}
    @Override public CompletionStage<PinataParty>activate(UUID partyId,String operationKey){AtomicReference<PinataChanged>event=new AtomicReference<>();return store.transact("pinata-activate:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"pinata-activate",operationKey))return parties.get(tx,partyId.toString()).orElseThrow().value();if(scan(tx).stream().anyMatch(value->value.status()==PinataParty.Status.ACTIVE))throw new IllegalStateException("PINATA_ALREADY_ACTIVE");var current=parties.get(tx,partyId.toString()).orElseThrow(()->new IllegalArgumentException("PINATA_NOT_FOUND"));PinataParty party=current.value();if(party.status()!=PinataParty.Status.PENDING)throw new IllegalStateException("PINATA_NOT_PENDING");PinataParty next=new PinataParty(party.id(),PinataParty.Status.ACTIVE,party.maximumHits(),party.totalHits(),party.playerHits(),party.eligibleVoters(),null,party.createdAt(),clock.instant(),null);parties.put(tx,party.id().toString(),next,current.revision());event.set(changed(next,null));return next;}).thenApply(value->{if(event.get()!=null)events.publish(event.get());return value;});}
    @Override public CompletionStage<PinataParty>hit(UUID partyId,UUID playerId,String operationKey){AtomicReference<PinataChanged>event=new AtomicReference<>();return store.transact("pinata-hit:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"pinata-hit",operationKey))return parties.get(tx,partyId.toString()).orElseThrow().value();var current=parties.get(tx,partyId.toString()).orElseThrow(()->new IllegalArgumentException("PINATA_NOT_FOUND"));PinataParty party=current.value();if(party.status()!=PinataParty.Status.ACTIVE)throw new IllegalStateException("PINATA_NOT_ACTIVE");if(policy.requireVoterForRewards()&&!party.eligibleVoters().contains(playerId))throw new SecurityException("PINATA_VOTER_REQUIRED");int playerHits=party.playerHits().getOrDefault(playerId,0);if(playerHits>=policy.pinata().maximumHitsPerPlayer())throw new IllegalStateException("PINATA_PLAYER_HIT_LIMIT");Map<UUID,Integer>hits=new LinkedHashMap<>(party.playerHits());hits.put(playerId,playerHits+1);int total=party.totalHits()+1;reward(tx,playerId,policy.pinata().hitReward(),"pinata-hit:"+party.id()+":"+playerId+":"+total,"pinata hit");PinataParty.Status status=total>=party.maximumHits()?PinataParty.Status.COMPLETED:PinataParty.Status.ACTIVE;if(status==PinataParty.Status.COMPLETED)reward(tx,playerId,policy.pinata().finalReward(),"pinata-final:"+party.id(),"pinata final");PinataParty next=new PinataParty(party.id(),status,party.maximumHits(),total,hits,party.eligibleVoters(),status==PinataParty.Status.COMPLETED?playerId:null,party.createdAt(),party.activatedAt(),status==PinataParty.Status.COMPLETED?clock.instant():null);parties.put(tx,party.id().toString(),next,current.revision());event.set(changed(next,playerId));return next;}).thenApply(value->{if(event.get()!=null)events.publish(event.get());return value;});}
    @Override public CompletionStage<PinataParty>cancel(UUID partyId,String operationKey){AtomicReference<PinataChanged>event=new AtomicReference<>();return store.transact("pinata-cancel:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"pinata-cancel",operationKey))return parties.get(tx,partyId.toString()).orElseThrow().value();var current=parties.get(tx,partyId.toString()).orElseThrow(()->new IllegalArgumentException("PINATA_NOT_FOUND"));PinataParty party=current.value();if(party.status()==PinataParty.Status.COMPLETED||party.status()==PinataParty.Status.CANCELLED)return party;PinataParty next=new PinataParty(party.id(),PinataParty.Status.CANCELLED,party.maximumHits(),party.totalHits(),party.playerHits(),party.eligibleVoters(),null,party.createdAt(),party.activatedAt(),clock.instant());parties.put(tx,party.id().toString(),next,current.revision());event.set(changed(next,null));return next;}).thenApply(value->{if(event.get()!=null)events.publish(event.get());return value;});}
    private void reward(com.magicstudios.magiccore.storage.DataTransaction tx,UUID player,EventsFile.EventReward reward,String key,String reason)throws Exception{if(reward.amountMinor()>0)EconomyTransactionSupport.credit(tx,player,currencies.get(reward.currency()),reward.amountMinor(),key,"events:vote-party",reason,clock.instant());}
    private List<PinataParty>scan(com.magicstudios.magiccore.storage.DataReader reader)throws Exception{List<PinataParty>result=new ArrayList<>();String after=null;while(true){var page=parties.scanPage(reader,after,250);for(var value:page)result.add(value.value());if(page.size()<250)return result;after=page.getLast().key();}}
    private PinataChanged changed(PinataParty value,UUID actor){return new PinataChanged(value.id(),value.status().name(),value.totalHits(),value.maximumHits(),actor,clock.instant());}
}
