package com.magicstudios.magiccore.modules.events;

import com.magicstudios.magiccore.api.DomainEventBus;
import com.magicstudios.magiccore.modules.economy.CurrencyDefinition;
import com.magicstudios.magiccore.modules.economy.EconomyTransactionSupport;
import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;
import java.time.Clock;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.atomic.AtomicReference;

public final class PersistentKothService implements KothService {
    private final TransactionalDataStore store;private final Clock clock;private final DomainEventBus events;private final Map<String,KothDefinition>definitions;private final Map<String,CurrencyDefinition>currencies;private final RecordRepository<KothRun>runs=new RecordRepository<>("events.koth.run",KothRun.class);
    public PersistentKothService(TransactionalDataStore store,Clock clock,DomainEventBus events,Collection<KothDefinition>definitions,Map<String,CurrencyDefinition>currencies){this.store=store;this.clock=clock;this.events=events;Map<String,KothDefinition>indexed=new LinkedHashMap<>();for(KothDefinition value:definitions)if(indexed.putIfAbsent(value.id(),value)!=null)throw new IllegalArgumentException("Duplicate KOTH "+value.id());this.definitions=Map.copyOf(indexed);this.currencies=Map.copyOf(currencies);}
    @Override public List<KothDefinition>definitions(){return definitions.values().stream().sorted(Comparator.comparing(KothDefinition::id)).toList();}
    @Override public CompletionStage<KothRun>start(String definitionId,String operationKey){KothDefinition definition=require(definitionId);AtomicReference<KothChanged>event=new AtomicReference<>();return store.transact("koth-start:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"koth-start",operationKey))throw new IllegalStateException("DUPLICATE_KOTH_START");if(scan(tx,1000).stream().anyMatch(value->value.definitionId().equals(definition.id())&&value.status()==KothRun.Status.ACTIVE))throw new IllegalStateException("KOTH_ALREADY_ACTIVE");KothRun run=KothRun.active(UUID.randomUUID(),definition.id(),clock.instant());runs.put(tx,run.id().toString(),run,0);event.set(changed(run));return run;}).thenApply(run->{events.publish(event.get());return run;});}
    @Override public CompletionStage<KothRun>sample(UUID runId,Collection<KothContender>contenders,Duration elapsed,String operationKey){if(elapsed.isNegative()||elapsed.isZero())throw new IllegalArgumentException("KOTH elapsed time must be positive");Map<String,KothContender>unique=new LinkedHashMap<>();for(KothContender contender:contenders)unique.putIfAbsent(contender.groupId(),contender);AtomicReference<KothChanged>event=new AtomicReference<>();return store.transact("koth-sample:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"koth-sample",operationKey))return runs.get(tx,runId.toString()).orElseThrow().value();var current=runs.get(tx,runId.toString()).orElseThrow(()->new IllegalArgumentException("KOTH_RUN_NOT_FOUND"));KothRun run=current.value();if(run.status()!=KothRun.Status.ACTIVE)return run;KothDefinition definition=require(run.definitionId());long progress=0;String holder="",name="";Set<UUID>recipients=Set.of();if(unique.size()==1){KothContender contender=unique.values().iterator().next();holder=contender.groupId();name=contender.displayName();progress=(holder.equals(run.holdingGroup())?run.capturedMillis():0)+elapsed.toMillis();recipients=contender.rewardRecipients();}KothRun next;if(progress>=definition.captureTime().toMillis()){var reward=definition.reward();CurrencyDefinition currency=currencies.get(reward.currency());for(UUID recipient:recipients)EconomyTransactionSupport.credit(tx,recipient,currency,reward.amountMinor(),"koth-reward:"+run.id()+":"+recipient,"events:koth",definition.id(),clock.instant());next=new KothRun(run.id(),run.definitionId(),KothRun.Status.COMPLETED,holder,name,definition.captureTime().toMillis(),holder,name,recipients,run.startedAt(),clock.instant(),clock.instant());}else next=new KothRun(run.id(),run.definitionId(),KothRun.Status.ACTIVE,holder,name,progress,"","",Set.of(),run.startedAt(),clock.instant(),null);runs.put(tx,run.id().toString(),next,current.revision());event.set(changed(next));return next;}).thenApply(run->{if(event.get()!=null)events.publish(event.get());return run;});}
    @Override public CompletionStage<KothRun>cancel(UUID runId,String operationKey){AtomicReference<KothChanged>event=new AtomicReference<>();return store.transact("koth-cancel:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"koth-cancel",operationKey))return runs.get(tx,runId.toString()).orElseThrow().value();var current=runs.get(tx,runId.toString()).orElseThrow(()->new IllegalArgumentException("KOTH_RUN_NOT_FOUND"));KothRun run=current.value();if(run.status()!=KothRun.Status.ACTIVE)return run;KothRun next=new KothRun(run.id(),run.definitionId(),KothRun.Status.CANCELLED,run.holdingGroup(),run.holdingName(),run.capturedMillis(),"","",Set.of(),run.startedAt(),clock.instant(),clock.instant());runs.put(tx,run.id().toString(),next,current.revision());event.set(changed(next));return next;}).thenApply(run->{if(event.get()!=null)events.publish(event.get());return run;});}
    @Override public CompletionStage<Optional<KothRun>>active(String definitionId){return store.read(reader->scan(reader,1000).stream().filter(value->value.definitionId().equalsIgnoreCase(definitionId)&&value.status()==KothRun.Status.ACTIVE).max(Comparator.comparing(KothRun::startedAt)));}
    @Override public CompletionStage<List<KothRun>>recent(int limit){if(limit<1||limit>100)throw new IllegalArgumentException("KOTH history limit must be 1..100");return store.read(reader->scan(reader,1000).stream().sorted(Comparator.comparing(KothRun::startedAt).reversed()).limit(limit).toList());}
    private List<KothRun>scan(com.magicstudios.magiccore.storage.DataReader reader,int limit)throws Exception{List<KothRun>result=new ArrayList<>();String after=null;while(result.size()<limit){var page=runs.scanPage(reader,after,Math.min(250,limit-result.size()));for(var value:page)result.add(value.value());if(page.size()<250)break;after=page.getLast().key();}return result;}
    private KothDefinition require(String id){KothDefinition value=definitions.get(id.toUpperCase(Locale.ROOT));if(value==null)throw new IllegalArgumentException("Unknown KOTH "+id);return value;}
    private KothChanged changed(KothRun run){return new KothChanged(run.id(),run.definitionId(),run.status().name(),run.holdingName(),run.winnerName(),clock.instant());}
}
