package com.magicstudios.magiccore.modules.securestorage;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.magicstudios.magiccore.capabilities.CapabilityService;
import com.magicstudios.magiccore.delivery.DeliveryTransactionSupport;
import com.magicstudios.magiccore.delivery.MailboxDelivery;
import com.magicstudios.magiccore.storage.IdempotencyKeys;
import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;

import java.time.Clock;
import java.time.Duration;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

public final class PersistentSecureStorageService implements SecureStorageService {
    public enum NestedContainerPolicy { DENY_ALL, DENY_NON_EMPTY, ALLOW }
    public enum CustomItemPolicy { DENY, ALLOW }
    private static final ObjectMapper JSON=new ObjectMapper().findAndRegisterModules();
    private final TransactionalDataStore store;private final CapabilityService capabilities;private final Clock clock;private final Duration leaseDuration;
    private final int maximumVaults,maximumItemPayloadBytes,maximumContainerPayloadBytes;private final String vaultRowsLimit,adminCapability;
    private final NestedContainerPolicy nestedPolicy;private final CustomItemPolicy customPolicy;
    private final RecordRepository<VirtualContainer>containers=new RecordRepository<>("secure-storage.container",VirtualContainer.class);
    private final RecordRepository<StorageLease>leases=new RecordRepository<>("secure-storage.lease",StorageLease.class);
    private final RecordRepository<ActiveLease>active=new RecordRepository<>("secure-storage.active",ActiveLease.class);
    private final RecordRepository<StorageCommit>commits=new RecordRepository<>("secure-storage.commit",StorageCommit.class);
    private final RecordRepository<OpenOperation>opens=new RecordRepository<>("secure-storage.open-operation",OpenOperation.class);

    public PersistentSecureStorageService(TransactionalDataStore store,CapabilityService capabilities,Clock clock,Duration leaseDuration,
                                          int maximumVaults,String vaultRowsLimit,int maximumItemPayloadBytes,int maximumContainerPayloadBytes,
                                          NestedContainerPolicy nestedPolicy,CustomItemPolicy customPolicy,String adminCapability){this.store=store;this.capabilities=capabilities;this.clock=clock;this.leaseDuration=leaseDuration;this.maximumVaults=maximumVaults;this.vaultRowsLimit=vaultRowsLimit;this.maximumItemPayloadBytes=maximumItemPayloadBytes;this.maximumContainerPayloadBytes=maximumContainerPayloadBytes;this.nestedPolicy=nestedPolicy;this.customPolicy=customPolicy;this.adminCapability=adminCapability;}

    @Override public CompletionStage<SecureStorageSession>open(UUID actorId,UUID ownerId,VirtualContainer.Type type,int containerIndex,String operationKey){if(containerIndex<0||(type==VirtualContainer.Type.ENDER_CHEST&&containerIndex!=0)||(type==VirtualContainer.Type.VAULT&&(containerIndex<1||containerIndex>maximumVaults)))throw new IllegalArgumentException("Invalid secure storage index");
        CompletableFuture<Boolean>authorized=actorId.equals(ownerId)?CompletableFuture.completedFuture(true):capabilities.has(actorId,adminCapability).toCompletableFuture();CompletableFuture<Integer>sizeFuture=(type==VirtualContainer.Type.ENDER_CHEST?CompletableFuture.completedFuture(27):capabilities.limit(ownerId,vaultRowsLimit).thenApply(rows->{if(rows<1)throw new SecurityException("VAULT_ENTITLEMENT_REQUIRED");return Math.min(6,rows)*9;}).toCompletableFuture());
        return CompletableFuture.allOf(authorized,sizeFuture).thenCompose(ignored->{if(!authorized.join())return CompletableFuture.failedFuture(new SecurityException("STORAGE_INSPECTION_DENIED"));int entitlement=sizeFuture.join();return store.transact("secure-storage-open:"+operationKey,tx->{var replay=opens.get(tx,operationKey);if(replay.isPresent()){StorageLease lease=leases.get(tx,replay.get().value().leaseId().toString()).orElseThrow().value();return session(tx,lease);}
            String key=key(ownerId,type,containerIndex);var currentActive=active.get(tx,key);if(currentActive.isPresent()){var leaseRecord=leases.get(tx,currentActive.get().value().leaseId().toString());if(leaseRecord.isPresent()&&leaseRecord.get().value().status()==StorageLease.Status.OPEN&&leaseRecord.get().value().expiresAt().isAfter(clock.instant()))throw new IllegalStateException("STORAGE_ALREADY_OPEN");if(leaseRecord.isPresent()){StorageLease old=leaseRecord.get().value();leases.put(tx,old.id().toString(),copy(old,StorageLease.Status.RECOVERED),leaseRecord.get().revision());}tx.delete("secure-storage.active",key,currentActive.get().revision());}
            var containerRecord=containers.get(tx,key);VirtualContainer container=containerRecord.map(RecordRepository.VersionedValue::value).orElse(new VirtualContainer(ownerId,type,containerIndex,entitlement,List.of(),clock.instant()));if(container.size()>entitlement)throw new SecurityException("STORAGE_ENTITLEMENT_REDUCED");long revision=containerRecord.map(RecordRepository.VersionedValue::revision).orElse(0L);var now=clock.instant();StorageLease lease=new StorageLease(UUID.randomUUID(),actorId,ownerId,type,containerIndex,container.size(),revision,StorageLease.Status.OPEN,now,now.plus(leaseDuration),now);leases.put(tx,lease.id().toString(),lease,0);active.put(tx,key,new ActiveLease(lease.id()),0);opens.put(tx,operationKey,new OpenOperation(operationKey,lease.id()),0);return new SecureStorageSession(lease,container,revision);});});}

    @Override public CompletionStage<StorageCommit>save(UUID actorId,UUID leaseId,long expectedRevision,List<StoredItem>items,String operationKey){List<StoredItem>snapshot=validateItems(items);return store.transact("secure-storage-save:"+operationKey,tx->{var replay=commits.get(tx,operationKey);if(replay.isPresent())return replay.get().value();if(!IdempotencyKeys.reserve(tx,"secure-storage-save",operationKey))throw new IllegalStateException("DUPLICATE_STORAGE_SAVE");var leaseRecord=leases.get(tx,leaseId.toString()).orElseThrow(()->new IllegalArgumentException("STORAGE_LEASE_NOT_FOUND"));StorageLease lease=leaseRecord.value();if(!lease.actorId().equals(actorId))throw new SecurityException("STORAGE_LEASE_ACTOR_MISMATCH");if(lease.status()!=StorageLease.Status.OPEN||!lease.expiresAt().isAfter(clock.instant()))throw new IllegalStateException("STORAGE_LEASE_EXPIRED");if(lease.expectedRevision()!=expectedRevision)throw new IllegalStateException("STORAGE_SESSION_REVISION_MISMATCH");String key=key(lease.ownerId(),lease.type(),lease.containerIndex());var containerRecord=containers.get(tx,key);long actual=containerRecord.map(RecordRepository.VersionedValue::revision).orElse(0L);if(actual!=expectedRevision)throw new IllegalStateException("STORAGE_STALE_REVISION");int size=containerRecord.map(value->value.value().size()).orElse(lease.size());if(snapshot.stream().anyMatch(item->item.slot()>=size))throw new IllegalArgumentException("STORAGE_SLOT_OUT_OF_BOUNDS");VirtualContainer container=new VirtualContainer(lease.ownerId(),lease.type(),lease.containerIndex(),size,snapshot,clock.instant());containers.put(tx,key,container,actual);StorageLease committed=copy(lease,StorageLease.Status.COMMITTED);leases.put(tx,lease.id().toString(),committed,leaseRecord.revision());var activeRecord=active.get(tx,key);if(activeRecord.isPresent()&&activeRecord.get().value().leaseId().equals(lease.id()))tx.delete("secure-storage.active",key,activeRecord.get().revision());StorageCommit commit=new StorageCommit(UUID.randomUUID(),lease.id(),lease.ownerId(),lease.type(),lease.containerIndex(),actual,actual+1,snapshot.size(),clock.instant());commits.put(tx,operationKey,commit,0);return commit;});}

    @Override public CompletionStage<Boolean>close(UUID actorId,UUID leaseId,String operationKey){return store.transact("secure-storage-close:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"secure-storage-close",operationKey))return false;var leaseRecord=leases.get(tx,leaseId.toString());if(leaseRecord.isEmpty()||leaseRecord.get().value().status()!=StorageLease.Status.OPEN)return false;StorageLease lease=leaseRecord.get().value();if(!lease.actorId().equals(actorId))throw new SecurityException("STORAGE_LEASE_ACTOR_MISMATCH");leases.put(tx,lease.id().toString(),copy(lease,StorageLease.Status.CLOSED),leaseRecord.get().revision());String key=key(lease.ownerId(),lease.type(),lease.containerIndex());var activeRecord=active.get(tx,key);if(activeRecord.isPresent()&&activeRecord.get().value().leaseId().equals(lease.id()))tx.delete("secure-storage.active",key,activeRecord.get().revision());return true;});}

    @Override public CompletionStage<Integer>recoverExpired(){return store.read(reader->{ArrayList<StorageLease>result=new ArrayList<>();String after=null;while(true){var page=leases.scanPage(reader,after,1000);page.stream().map(RecordRepository.KeyedVersionedValue::value).filter(value->value.status()==StorageLease.Status.OPEN&&!value.expiresAt().isAfter(clock.instant())).forEach(result::add);if(page.size()<1000)break;after=page.getLast().key();}return result;}).thenCompose(expired->{CompletableFuture<?>[]tasks=expired.stream().map(lease->store.transact("secure-storage-recover:"+lease.id(),tx->{var current=leases.get(tx,lease.id().toString());if(current.isEmpty()||current.get().value().status()!=StorageLease.Status.OPEN)return false;leases.put(tx,lease.id().toString(),copy(current.get().value(),StorageLease.Status.RECOVERED),current.get().revision());String key=key(lease.ownerId(),lease.type(),lease.containerIndex());var activeRecord=active.get(tx,key);if(activeRecord.isPresent()&&activeRecord.get().value().leaseId().equals(lease.id()))tx.delete("secure-storage.active",key,activeRecord.get().revision());return true;}).toCompletableFuture()).toArray(CompletableFuture[]::new);return CompletableFuture.allOf(tasks).thenApply(ignored->expired.size());});}

    @Override public CompletionStage<Boolean>enqueueRecovery(UUID ownerId,UUID leaseId,List<StoredItem>items,String operationKey){List<StoredItem>snapshot=validateItems(items);return store.transact("secure-storage-mailbox:"+operationKey,tx->{if(!IdempotencyKeys.reserve(tx,"secure-storage-recovery",operationKey))return false;MailboxDelivery delivery=MailboxDelivery.pending(UUID.randomUUID(),ownerId,operationKey,"magiccore/secure-storage-recovery-v1",JSON.writeValueAsBytes(new RecoveryPayload(leaseId,snapshot)),clock.instant());DeliveryTransactionSupport.enqueue(tx,delivery);return true;});}

    private SecureStorageSession session(com.magicstudios.magiccore.storage.DataReader reader,StorageLease lease)throws Exception{String key=key(lease.ownerId(),lease.type(),lease.containerIndex());var current=containers.get(reader,key);VirtualContainer container=current.map(RecordRepository.VersionedValue::value).orElse(new VirtualContainer(lease.ownerId(),lease.type(),lease.containerIndex(),lease.size(),List.of(),clock.instant()));return new SecureStorageSession(lease,container,current.map(RecordRepository.VersionedValue::revision).orElse(0L));}
    private List<StoredItem>validateItems(List<StoredItem>items){List<StoredItem>snapshot=List.copyOf(items);Set<Integer>slots=new HashSet<>();int total=0;for(StoredItem item:snapshot){if(!slots.add(item.slot()))throw new IllegalArgumentException("DUPLICATE_STORAGE_SLOT");if(item.payloadBytes()>maximumItemPayloadBytes)throw new IllegalArgumentException("ITEM_PAYLOAD_TOO_LARGE");total=Math.addExact(total,item.payloadBytes());if(item.container()&&(nestedPolicy==NestedContainerPolicy.DENY_ALL||(nestedPolicy==NestedContainerPolicy.DENY_NON_EMPTY&&item.nestedContainerNonEmpty())))throw new IllegalArgumentException("NESTED_CONTAINER_POLICY_DENIED");if(item.customItem()&&customPolicy==CustomItemPolicy.DENY)throw new IllegalArgumentException("CUSTOM_ITEM_POLICY_DENIED");}if(total>maximumContainerPayloadBytes)throw new IllegalArgumentException("CONTAINER_PAYLOAD_TOO_LARGE");return snapshot;}
    private static int maximumSlot(List<StoredItem>items){return Math.max(9,items.stream().mapToInt(StoredItem::slot).max().orElse(8)+1);}
    private StorageLease copy(StorageLease lease,StorageLease.Status status){return new StorageLease(lease.id(),lease.actorId(),lease.ownerId(),lease.type(),lease.containerIndex(),lease.size(),lease.expectedRevision(),status,lease.openedAt(),lease.expiresAt(),clock.instant());}
    private static String key(UUID owner,VirtualContainer.Type type,int index){return type+":"+owner+":"+index;}
    private record ActiveLease(UUID leaseId){}
    private record OpenOperation(String operationKey,UUID leaseId){}
    public record RecoveryPayload(UUID leaseId,List<StoredItem>items){public RecoveryPayload{items=List.copyOf(items);}}
}
