package com.magicstudios.magiccore.imports;

import com.magicstudios.magiccore.storage.RecordRepository;
import com.magicstudios.magiccore.storage.TransactionalDataStore;
import java.time.Clock;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

public final class PersistentImportService implements ImportService {
 private final TransactionalDataStore store;private final Clock clock;private final RecordRepository<ImportJob>jobs=new RecordRepository<>("imports.job",ImportJob.class);
 public PersistentImportService(TransactionalDataStore store,Clock clock){this.store=store;this.clock=clock;}
 @Override public CompletionStage<ImportPreview>preview(String id,ImportSource source,ImportTarget target,Map<String,String>mapping){validateIdentity(id,source,target);for(String required:target.requiredFields())if(!mapping.containsKey(required))throw new IllegalArgumentException("Missing mapping for "+required);
  Scan scan=new Scan();return scanPreview(source,target,mapping,null,scan).thenCompose(ignored->{ImportPreview preview=new ImportPreview(id,source.sourceId(),target.targetId(),source.fingerprint(),mapping,scan.total,scan.valid,scan.issues);
   ImportJob job=new ImportJob(id,source.sourceId(),target.targetId(),source.fingerprint(),mapping,null,0,0,ImportJob.Status.PREVIEWED,clock.instant());return store.transact("import-preview:"+id,tx->{var current=jobs.get(tx,id);jobs.put(tx,id,job,current.map(RecordRepository.VersionedValue::revision).orElse(0L));return preview;});});}
 @Override public CompletionStage<ImportRun>execute(String id,ImportSource source,ImportTarget target,int batchSize){if(batchSize<1||batchSize>1000)throw new IllegalArgumentException("batch size must be 1..1000");return require(id,source,target).thenCompose(job->runPage(job,source,target,batchSize,new ArrayList<>()));}
 @Override public CompletionStage<ImportRun>reconcile(String id,ImportSource source,ImportTarget target,int batchSize){if(batchSize<1||batchSize>1000)throw new IllegalArgumentException("batch size must be 1..1000");return require(id,source,target).thenCompose(job->{ArrayList<ImportIssue>issues=new ArrayList<>();long[]verified={0};return verifyPage(source,target,job.mapping(),null,batchSize,issues,verified).thenCompose(ignored->update(job.importId(),current->new ImportJob(current.importId(),current.sourceId(),current.targetId(),current.fingerprint(),current.mapping(),current.checkpoint(),current.appliedRows(),verified[0],issues.isEmpty()?ImportJob.Status.COMPLETE:ImportJob.Status.RECONCILIATION_REQUIRED,clock.instant())).thenApply(updated->new ImportRun(updated,issues)));});}
 @Override public CompletionStage<Optional<ImportJob>>job(String id){return store.read(reader->jobs.get(reader,id).map(RecordRepository.VersionedValue::value));}
 private CompletionStage<Void>scanPreview(ImportSource source,ImportTarget target,Map<String,String>mapping,String cursor,Scan scan){return source.read(cursor,500).thenCompose(page->{for(ImportRow raw:page.rows()){ImportRow row=map(raw,mapping);List<String>issues=target.validate(row);scan.total++;if(issues.isEmpty())scan.valid++;else issues.forEach(message->{if(scan.issues.size()<1000)scan.issues.add(new ImportIssue(row.key(),message));});}return page.done()?CompletableFuture.completedFuture(null):scanPreview(source,target,mapping,page.nextCursor(),scan);});}
 private CompletionStage<ImportRun>runPage(ImportJob job,ImportSource source,ImportTarget target,int size,List<ImportIssue>issues){return source.read(job.checkpoint(),size).thenCompose(page->applyRows(job,source,target,page.rows(),0,issues).thenCompose(current->{if(page.done())return update(current.importId(),value->new ImportJob(value.importId(),value.sourceId(),value.targetId(),value.fingerprint(),value.mapping(),value.checkpoint(),value.appliedRows(),value.verifiedRows(),issues.isEmpty()?ImportJob.Status.COMPLETE:ImportJob.Status.RECONCILIATION_REQUIRED,clock.instant())).thenApply(done->new ImportRun(done,issues));return runPage(current,source,target,size,issues);}));}
 private CompletionStage<ImportJob>applyRows(ImportJob job,ImportSource source,ImportTarget target,List<ImportRow>rows,int index,List<ImportIssue>issues){if(index>=rows.size())return CompletableFuture.completedFuture(job);ImportRow row=map(rows.get(index),job.mapping());List<String>validation=target.validate(row);if(!validation.isEmpty()){validation.forEach(message->issues.add(new ImportIssue(row.key(),message)));return checkpoint(job,row.key(),false).thenCompose(next->applyRows(next,source,target,rows,index+1,issues));}
  return target.apply(row,"import:"+job.importId()+":"+row.key()).thenCompose(ignored->target.verify(row)).thenCompose(verified->{if(!verified)issues.add(new ImportIssue(row.key(),"Post-apply verification failed"));return checkpoint(job,row.key(),verified).thenCompose(next->applyRows(next,source,target,rows,index+1,issues));});}
 private CompletionStage<ImportJob>checkpoint(ImportJob job,String cursor,boolean verified){return update(job.importId(),current->new ImportJob(current.importId(),current.sourceId(),current.targetId(),current.fingerprint(),current.mapping(),cursor,current.appliedRows()+1,current.verifiedRows()+(verified?1:0),ImportJob.Status.RUNNING,clock.instant()));}
 private CompletionStage<Void>verifyPage(ImportSource source,ImportTarget target,Map<String,String>mapping,String cursor,int size,List<ImportIssue>issues,long[]verified){return source.read(cursor,size).thenCompose(page->verifyRows(page.rows(),0,target,mapping,issues,verified).thenCompose(ignored->page.done()?CompletableFuture.completedFuture(null):verifyPage(source,target,mapping,page.nextCursor(),size,issues,verified)));}
 private CompletionStage<Void>verifyRows(List<ImportRow>rows,int index,ImportTarget target,Map<String,String>mapping,List<ImportIssue>issues,long[]verified){if(index>=rows.size())return CompletableFuture.completedFuture(null);ImportRow row=map(rows.get(index),mapping);return target.verify(row).thenCompose(ok->{if(ok)verified[0]++;else issues.add(new ImportIssue(row.key(),"Reconciliation mismatch"));return verifyRows(rows,index+1,target,mapping,issues,verified);});}
 private CompletionStage<ImportJob>require(String id,ImportSource source,ImportTarget target){return job(id).thenApply(found->{ImportJob value=found.orElseThrow(()->new IllegalStateException("IMPORT_NOT_PREVIEWED"));if(!value.sourceId().equals(source.sourceId())||!value.targetId().equals(target.targetId())||!value.fingerprint().equals(source.fingerprint()))throw new IllegalStateException("IMPORT_SOURCE_OR_TARGET_CHANGED");return value;});}
 private CompletionStage<ImportJob>update(String id,java.util.function.UnaryOperator<ImportJob>change){return store.transact("import-job:"+id+":"+java.util.UUID.randomUUID(),tx->{var current=jobs.get(tx,id).orElseThrow();ImportJob updated=change.apply(current.value());jobs.put(tx,id,updated,current.revision());return updated;});}
 private static ImportRow map(ImportRow raw,Map<String,String>mapping){java.util.LinkedHashMap<String,String>values=new java.util.LinkedHashMap<>();mapping.forEach((canonical,source)->values.put(canonical,raw.values().getOrDefault(source,"")));return new ImportRow(raw.key(),values);}
 private static void validateIdentity(String id,ImportSource source,ImportTarget target){if(!id.matches("[a-zA-Z0-9._-]{1,64}")||source.sourceId().isBlank()||target.targetId().isBlank())throw new IllegalArgumentException("Invalid import identity");}
 private static final class Scan{long total,valid;final List<ImportIssue>issues=new ArrayList<>();}
}
