package com.magicstudios.magiccore.gui;

import com.magicstudios.magiccore.config.model.SecureStorageFile;
import com.magicstudios.magiccore.modules.securestorage.*;
import com.magicstudios.magiccore.platform.SchedulerFacade;
import net.kyori.adventure.text.Component;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.BlockStateMeta;
import org.bukkit.inventory.meta.BundleMeta;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.plugin.Plugin;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/** Mutable virtual-container UI backed by an exclusive lease and CAS commit. */
public final class SecureStorageController implements Listener,AutoCloseable {
    private final Plugin plugin;private final SchedulerFacade scheduler;private final SecureStorageService service;private final SecureStorageFile policy;private final SecureStorageItemPolicy itemPolicy;private final Map<UUID,OpenView>views=new ConcurrentHashMap<>();private volatile boolean closed;
    public SecureStorageController(Plugin plugin,SchedulerFacade scheduler,SecureStorageService service,SecureStorageFile policy){this.plugin=plugin;this.scheduler=scheduler;this.service=service;this.policy=policy;this.itemPolicy=new SecureStorageItemPolicy(policy.maximumItemPayloadBytes(),policy.maximumContainerPayloadBytes(),policy.nestedContainerPolicy(),policy.customItemPolicy());}
    public void open(Player player,VirtualContainer.Type type,int index){UUID playerId=player.getUniqueId();service.open(playerId,playerId,type,index,"storage-gui-open:"+playerId+":"+type+":"+index+":"+UUID.randomUUID()).whenComplete((session,failure)->{if(failure!=null){scheduler.executeEntity(player,()->player.sendMessage(Component.text("Storage could not open: "+root(failure))),()->{});return;}scheduler.executeEntity(player,()->show(player,session),()->service.close(playerId,session.lease().id(),"storage-retired:"+session.lease().id()));});}
    private void show(Player player,SecureStorageSession session){if(closed){service.close(player.getUniqueId(),session.lease().id(),"storage-controller-closed:"+session.lease().id());return;}Holder holder=new Holder(session.lease().id());Inventory inventory=Bukkit.createInventory(holder,session.container().size(),Component.text(session.container().type()==VirtualContainer.Type.VAULT?"Vault "+session.container().index():"Secure Ender Chest"));holder.inventory=inventory;for(StoredItem stored:session.container().items())try{inventory.setItem(stored.slot(),ItemStack.deserializeBytes(Base64.getDecoder().decode(stored.payloadBase64())));}catch(RuntimeException failure){plugin.getLogger().severe("Secure storage item could not deserialize for lease "+session.lease().id()+": "+failure.getMessage());service.close(player.getUniqueId(),session.lease().id(),"storage-corrupt:"+session.lease().id());player.sendMessage(Component.text("Storage contains an unreadable item and was kept closed."));return;}views.put(player.getUniqueId(),new OpenView(session,holder));player.openInventory(inventory);}
    @EventHandler(priority=EventPriority.HIGHEST)public void onClick(InventoryClickEvent event){if(!(event.getView().getTopInventory().getHolder(false)instanceof Holder))return;if(!(event.getWhoClicked()instanceof Player player)){event.setCancelled(true);return;}ItemStack incoming=incoming(event,player);if(incoming!=null&&!incoming.getType().isAir()&&!accepts(incoming,event.getView().getTopInventory(),1)){event.setCancelled(true);player.sendMessage(Component.text("That item is not allowed in secure storage."));}}
    @EventHandler(priority=EventPriority.HIGHEST)public void onDrag(InventoryDragEvent event){if(!(event.getView().getTopInventory().getHolder(false)instanceof Holder))return;long topSlots=event.getRawSlots().stream().filter(slot->slot<event.getView().getTopInventory().getSize()).count();if(topSlots>0&&!accepts(event.getOldCursor(),event.getView().getTopInventory(),(int)topSlots)){event.setCancelled(true);if(event.getWhoClicked()instanceof Player player)player.sendMessage(Component.text("That item is not allowed in secure storage."));}}
    @EventHandler public void onClose(InventoryCloseEvent event){if(!(event.getInventory().getHolder(false)instanceof Holder holder))return;OpenView view=views.remove(event.getPlayer().getUniqueId());if(view==null||!view.holder().leaseId.equals(holder.leaseId))return;Player player=(Player)event.getPlayer();List<StoredItem>items;try{items=serialize(event.getInventory());}catch(RuntimeException failure){plugin.getLogger().severe("Could not serialize secure storage lease "+holder.leaseId+": "+failure.getMessage());service.close(player.getUniqueId(),holder.leaseId,"storage-serialization-failed:"+holder.leaseId);player.sendMessage(Component.text("Storage save was rejected; the previous committed contents remain authoritative."));return;}service.save(player.getUniqueId(),holder.leaseId,view.session().revision(),items,"storage-gui-save:"+holder.leaseId).whenComplete((commit,failure)->{if(failure==null){scheduler.executeEntity(player,()->player.sendMessage(Component.text("Secure storage saved at revision "+commit.revision()+".")),()->{});return;}service.enqueueRecovery(view.session().container().ownerId(),holder.leaseId,items,"storage-gui-recovery:"+holder.leaseId).whenComplete((queued,recoveryFailure)->{service.close(player.getUniqueId(),holder.leaseId,"storage-save-failed:"+holder.leaseId);scheduler.executeEntity(player,()->player.sendMessage(Component.text(recoveryFailure==null?"Storage save conflicted; the item snapshot was placed in the recovery mailbox.":"Storage save failed; contact an administrator with lease "+holder.leaseId+".")),()->{});if(recoveryFailure!=null)plugin.getLogger().severe("Secure storage recovery failed for lease "+holder.leaseId+": "+root(recoveryFailure));});});}
    @EventHandler public void onQuit(PlayerQuitEvent event){OpenView view=views.get(event.getPlayer().getUniqueId());if(view!=null)event.getPlayer().closeInventory();}
    private ItemStack incoming(InventoryClickEvent event,Player player){int top=event.getView().getTopInventory().getSize();if(event.isShiftClick()&&event.getRawSlot()>=top)return event.getCurrentItem();if(event.getRawSlot()<0||event.getRawSlot()>=top)return null;if(event.getClick()==ClickType.NUMBER_KEY){int button=event.getHotbarButton();return button>=0?player.getInventory().getItem(button):null;}if(event.getClick()==ClickType.SWAP_OFFHAND)return player.getInventory().getItemInOffHand();return event.getCursor();}
    private boolean accepts(ItemStack item,Inventory current,int multiplier){try{byte[]payload=item.serializeAsBytes();boolean container=isContainer(item),nonEmpty=nonEmptyContainer(item),custom=custom(item);long total=0;for(ItemStack existing:current.getContents())if(existing!=null&&!existing.getType().isAir())total+=existing.serializeAsBytes().length;return itemPolicy.accepts(payload.length,container,nonEmpty,custom,total,multiplier);}catch(RuntimeException failure){return false;}}
    private List<StoredItem>serialize(Inventory inventory){List<StoredItem>items=new ArrayList<>();for(int slot=0;slot<inventory.getSize();slot++){ItemStack item=inventory.getItem(slot);if(item==null||item.getType().isAir())continue;byte[]payload=item.serializeAsBytes();items.add(new StoredItem(slot,item.getType().getKey().toString(),item.getAmount(),Base64.getEncoder().encodeToString(payload),isContainer(item),nonEmptyContainer(item),custom(item)));}return List.copyOf(items);}
    private static boolean isContainer(ItemStack item){return item.getItemMeta()instanceof BlockStateMeta||item.getItemMeta()instanceof BundleMeta;}
    private static boolean nonEmptyContainer(ItemStack item){if(item.getItemMeta()instanceof BlockStateMeta meta&&meta.getBlockState()instanceof org.bukkit.inventory.InventoryHolder holder)return Arrays.stream(holder.getInventory().getContents()).anyMatch(value->value!=null&&!value.getType().isAir());if(item.getItemMeta()instanceof BundleMeta bundle)return bundle.hasItems();return false;}
    private static boolean custom(ItemStack item){PersistentDataContainer data=item.getItemMeta().getPersistentDataContainer();return !data.getKeys().isEmpty();}
    @Override public void close(){closed=true;HandlerList.unregisterAll(this);for(UUID playerId:new ArrayList<>(views.keySet())){Player player=plugin.getServer().getPlayer(playerId);if(player!=null)scheduler.executeEntity(player,player::closeInventory,()->{});}views.clear();}
    private static String root(Throwable failure){Throwable value=failure;while(value.getCause()!=null)value=value.getCause();return value.getMessage();}
    private record OpenView(SecureStorageSession session,Holder holder){}
    private static final class Holder implements InventoryHolder{private final UUID leaseId;private Inventory inventory;private Holder(UUID leaseId){this.leaseId=leaseId;}@Override public Inventory getInventory(){return inventory;}}
}
