package com.magicstudios.magiccore.phasesix;

import com.magicstudios.magiccore.audit.PersistentAuditService;import com.magicstudios.magiccore.delivery.PersistentDeliveryMailbox;import com.magicstudios.magiccore.modules.billford.*;import com.magicstudios.magiccore.modules.economy.*;import com.magicstudios.magiccore.modules.shop.*;import com.magicstudios.magiccore.platform.BoundedIoExecutor;import com.magicstudios.magiccore.storage.InMemoryTransactionalDataStore;import org.junit.jupiter.api.Test;
import java.time.*;import java.util.*;import java.util.concurrent.CompletableFuture;import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;

class BillfordServiceTest{
 @Test void exchangeEnforcesStockLimitCooldownExactRemovalAndSingleSettlement(){var store=new InMemoryTransactionalDataStore(new BoundedIoExecutor(2,64,"billford-test"));try{Clock clock=Clock.fixed(Instant.parse("2026-08-11T12:00:00Z"),ZoneOffset.UTC);AtomicInteger removals=new AtomicInteger();BatchInventoryRemovalPort inventory=(player,lines,key)->{removals.incrementAndGet();assertThat(lines).singleElement().extracting(BatchInventoryRemovalPort.RemovalLine::quantity).isEqualTo(32);return CompletableFuture.completedFuture(new BatchInventoryRemovalPort.BatchRemovalReceipt(true,"REMOVED","payload"));};CurrencyDefinition coins=new CurrencyDefinition("COINS","Coins","$",2,0,100_000);var service=new PersistentBillfordService(store,inventory,List.of(recipe("coins",2,2,Duration.ZERO,new BillfordReward("coins",BillfordReward.Type.CURRENCY,1,"COINS",500,"AIR",0,""))),Map.of("COINS",coins),new PersistentAuditService(store),clock);UUID player=UUID.randomUUID();BillfordCandidate iron=new BillfordCandidate("minecraft:iron_ingot",ItemFingerprint.of("IRON_INGOT",new byte[]{1}),32,false);
   assertThat(service.preview(player,"coins").toCompletableFuture().join().eligible()).isTrue();var first=service.exchange(player,"coins",List.of(iron),"exchange-1").toCompletableFuture().join();assertThat(first.status()).isEqualTo(BillfordExchange.Status.SETTLED);assertThat(EconomyTransactionSupport.balance(storeReader(store),player,coins).minorUnits()).isEqualTo(500);var preview=service.preview(player,"coins").toCompletableFuture().join();assertThat(preview.remainingStock()).isEqualTo(1);assertThat(preview.playerClaims()).isEqualTo(1);assertThatThrownBy(()->service.exchange(player,"coins",List.of(iron),"exchange-1").toCompletableFuture().join()).hasRootCauseMessage("DUPLICATE_EXCHANGE");assertThat(removals).hasValue(1);
 }catch(Exception failure){throw new AssertionError(failure);}finally{store.close();}}
 @Test void failedRemovalRollsBackReservationAndItemRewardUsesMailbox(){var store=new InMemoryTransactionalDataStore(new BoundedIoExecutor(2,64,"billford-mailbox"));try{Clock clock=Clock.fixed(Instant.parse("2026-08-11T12:00:00Z"),ZoneOffset.UTC);CurrencyDefinition coins=new CurrencyDefinition("COINS","Coins","$",2,0,100_000);BatchInventoryRemovalPort stale=(player,lines,key)->CompletableFuture.completedFuture(new BatchInventoryRemovalPort.BatchRemovalReceipt(false,"STALE",""));var failed=new PersistentBillfordService(store,stale,List.of(recipe("item",1,1,Duration.ofMinutes(5),new BillfordReward("diamond",BillfordReward.Type.ITEM,1,"COINS",0,"DIAMOND",2,""))),Map.of("COINS",coins),new PersistentAuditService(store),clock);UUID player=UUID.randomUUID();BillfordCandidate iron=new BillfordCandidate("minecraft:iron_ingot",ItemFingerprint.of("IRON_INGOT",new byte[]{1}),32,false);assertThatThrownBy(()->failed.exchange(player,"item",List.of(iron),"failed").toCompletableFuture().join()).hasRootCauseMessage("STALE");assertThat(failed.preview(player,"item").toCompletableFuture().join()).extracting(BillfordPreview::remainingStock,BillfordPreview::playerClaims).containsExactly(1,0);
   BatchInventoryRemovalPort ok=(id,lines,key)->CompletableFuture.completedFuture(new BatchInventoryRemovalPort.BatchRemovalReceipt(true,"REMOVED","payload"));var success=new PersistentBillfordService(store,ok,List.of(recipe("item",1,1,Duration.ZERO,new BillfordReward("diamond",BillfordReward.Type.ITEM,1,"COINS",0,"DIAMOND",2,""))),Map.of("COINS",coins),new PersistentAuditService(store),clock);var settled=success.exchange(player,"item",List.of(iron),"success").toCompletableFuture().join();assertThat(settled.status()).isEqualTo(BillfordExchange.Status.SETTLED);assertThat(new PersistentDeliveryMailbox(store,clock).pending(player,10).toCompletableFuture().join()).singleElement().extracting(value->value.payloadType()).isEqualTo("magiccore/shop-purchase-v1");
 }finally{store.close();}}
 private static BillfordRecipe recipe(String id,int stock,int limit,Duration cooldown,BillfordReward reward){return new BillfordRecipe(id,id,stock,limit,cooldown,List.of(new BillfordIngredient("minecraft:iron_ingot",32)),List.of(reward));}
 private static com.magicstudios.magiccore.storage.DataReader storeReader(InMemoryTransactionalDataStore store){return new com.magicstudios.magiccore.storage.DataReader(){public Optional<com.magicstudios.magiccore.storage.StoredRecord>get(String namespace,String key)throws Exception{return store.read(reader->reader.get(namespace,key)).toCompletableFuture().join();}public List<com.magicstudios.magiccore.storage.StoredRecord>scan(String namespace,String after,int limit)throws Exception{return store.read(reader->reader.scan(namespace,after,limit)).toCompletableFuture().join();}};}
}
